### ISSUE TITLE
[Bug] Option 'target=ES3' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.

### ISSUE THREAD

**Issue by dohuuhuy** [apache/echarts#19585] opened 2024-02-02 05:03 UTC
### Version

"echarts": "^5.4.3",

### Link to Minimal Reproduction

Option 'target=ES3' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.

### Steps to Reproduce

"echarts": "^5.4.3",

### Current Behavior

Option 'target=ES3' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.

### Expected Behavior

Option 'target=ES3' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by dohuuhuy** [comment] 2024-02-02 05:04
source nextjs  "next": "14.1.0",    "typescript": "^5"

**Comment by plainheart** [comment] 2024-02-02 14:37
duplicate of #19560

**Closed by plainheart** 2024-02-02 14:37 UTC
Labels: bug, pending, duplicate, en
