### ISSUE TITLE
SVG renderer issues

### ISSUE THREAD

**Issue by jarben** [apache/echarts#7332] opened 2017-12-20 11:04 UTC
Version: 3.8.5

I've managed to get some time and try the SVG renderer beta. Apart from some issues it works really well! 

Below is a list of uses cases, pls let me know if you need to provide sample code to some of the cases: 

(left = canvas, right = svg)

1.  borderWidth on itemStyle doesn't seem to be applied (seems to always use 1px):
![image](https://user-images.githubusercontent.com/561365/34203539-ceb00888-e57b-11e7-8184-4a95d3bcbdbc.png)

2. Pie chart shows selected pieces on load, hovering over it reveals them: 
![image](https://user-images.githubusercontent.com/561365/34203576-ffa237fe-e57b-11e7-8678-c69e55bf138f.png)

3. Gradient doesn't seem to work as in canvas: 
![image](https://user-images.githubusercontent.com/561365/34203802-a5e78ce0-e57c-11e7-84f0-e081f883a9db.png)

4. In some cases lines or areas are cut off. The issue is that this doesn't happen always so reproducing it is tricky: 
![image](https://user-images.githubusercontent.com/561365/34203872-dca003c0-e57c-11e7-8ef7-bcc3810a6e09.png)

5. In some cases maps get this black background (not all maps): 
![image](https://user-images.githubusercontent.com/561365/34203957-2525b23e-e57d-11e7-8c1b-3d30059f9603.png)

6. Heatmaps shows as below (+ visual map legend gets incorrect gradient)
![image](https://user-images.githubusercontent.com/561365/34204016-65517834-e57d-11e7-9b02-00e1ce8f62f8.png)

7. Gauge with gradient issue: 
![image](https://user-images.githubusercontent.com/561365/34204043-81600bd0-e57d-11e7-8a58-3e670ae818ce.png)

I'm happy to send example codes, just tell me which cases are not known issues (since its beta) and I can make them. It would be also great if the playground app allows to use SVG renderer so I can test the code in the same environment. 

Again, this is amazing feature so thanks for your hard work!

**Comment by jarben** [comment] 2017-12-20 11:08
Ah, one more thing - animation of lines symbol only happens in canvas:

![image](https://user-images.githubusercontent.com/561365/34204300-6137b3c0-e57e-11e7-825a-3e2eb4925a6c.png)

**Comment by Ovilia** [comment] 2017-12-21 02:17
@jarben 
Thanks Jarben! It's very nice of you to provide this info for us. 
After a general look of the cases, I think many of the bugs have been fixed since 3.8.5, like the gradient problem. I will check it and fix the other bugs. Thanks again!

**Comment by jarben** [comment] 2017-12-21 04:26
That's great to hear @Ovilia , looking forward to test 3.8.6+, pls let me know if you need more info or code samples. thanks, Jaro

**Comment by Ovilia** [comment] 2018-01-09 05:45
Hi @jarben , here's some updates on the bugs reported above. Please help have a look, and thanks for your contribution again! 😃 

**Fixed:**
Problem 1: This bug is due to render order of fill and stroke. Fixed in https://github.com/ecomfe/zrender/commit/7741d698b43b5216d851de4c3a7152312d2e090d .
Problem 2: I'm not sure if this is fixed by https://github.com/ecomfe/zrender/commit/01b955f31aee95c9347d83cccce6ac62926aa16f, please help test out.
Problem 3 and 7: Gradient problems were fixed.

**More information needed:**
Problem 4 and 5: Could you provide the code to reproduce these problems?

**Not supported:**
Problem 6: Heatmap is created using Canvas blending, so it is not supported by SVG until we have other plans.

**Comment by jarben** [comment] 2018-01-09 06:26
Hi @Ovilia, thanks for your update! I'll do some testing & provide code samples asap, is there any deadline for 3.8.6? Thanks!!!

**Comment by Ovilia** [comment] 2018-01-09 07:02
@jarben Actually, we are about to release 4.0 beta! 😄 
If feedback can be given before 12th Jan, it's more likely to be fixed in this version. But don't be worried if you are too busy to test them, we can always fix it in future versions.

**Comment by jarben** [comment] 2018-01-09 08:19
That's a great news! Will try to allocate some time asap:)

**Comment by jarben** [comment] 2018-01-09 12:19
I have managed to get some time for testing, here are results: 
1.-4. Can't reproduce anymore, great!
5. Dark map background - pls see this example: 
[map-background.zip](https://github.com/ecomfe/echarts/files/1614920/map-background.zip)
6. Heatmap: makes sense

Also found couple of minor differences: 
I. Bar labels disappear after animation finishes, rather than before it finishes (canvas)

Click on Male legend to disable this category, Male labels in the bar chart disappear differently than in cavas: 
![image](https://user-images.githubusercontent.com/561365/34720092-d0a125b0-f53d-11e7-9846-a4b6729c31b1.png)

II. Mark point label is not centered as in canvas: 
![image](https://user-images.githubusercontent.com/561365/34720161-03a70d76-f53e-11e7-9512-93b238b3eea1.png)

Also found some issues in the latest build, not sure whether this is a good place to post them as it's not SVG related and potentially known issues. Anyway, here it is: 

A) Shifting legend colors in PIE charts:
Click on item 1 in the pie chart = item 7 changes color
![image](https://user-images.githubusercontent.com/561365/34719441-2acc0a4e-f53b-11e7-8a7d-3af960fffb2e.png)
[pie-legend-colors.zip](https://github.com/ecomfe/echarts/files/1615005/pie-legend-colors.zip)

B) Bar chart changes color when using data zoom (items outside of original start/end get default color rather than item's color)
![image](https://user-images.githubusercontent.com/561365/34719560-921629fa-f53b-11e7-8e52-c9a8d65b1b39.png)
Example: 
[histogram-item-color.zip](https://github.com/ecomfe/echarts/files/1614953/histogram-item-color.zip)

C) Sankey shows an error in console: 
![image](https://user-images.githubusercontent.com/561365/34719609-b6173722-f53b-11e7-8fd5-36bc774b2eb5.png)
Example: 
[sankey.zip](https://github.com/ecomfe/echarts/files/1614960/sankey.zip)

D) Heatmap and punch cards don't show up:
![image](https://user-images.githubusercontent.com/561365/34719710-14aa5c88-f53c-11e7-998a-766a136cc1fc.png)
Examples: 
[heat-map.zip](https://github.com/ecomfe/echarts/files/1614962/heat-map.zip)
[punch-card.zip](https://github.com/ecomfe/echarts/files/1614964/punch-card.zip)

E) Pie timeline shows an error after clicking on timeline: 
![image](https://user-images.githubusercontent.com/561365/34719835-96cdd05a-f53c-11e7-9eb8-0596a8c88ce9.png)
[pie-timeline.zip](https://github.com/ecomfe/echarts/files/1614970/pie-timeline.zip)

Looking forward for the realease, sunburst is looking great!!

**Comment by Ovilia** [comment] 2018-01-10 02:49
@jarben Thanks for that!!! I'll follow up and test them. :)

**Comment by jarben** [comment] 2018-01-10 04:37
Brilliant, thanks @Ovilia !

**Comment by palmerye** [comment] 2018-01-12 06:16
@Ovilia I also find the issue about Heatmaps in 3.8.5 by SVG renderer.

I see ECharts 4.0 will be released on 12th Jan from the ECharts weibo.

will fix this issue in 4.0 version?

**Comment by Ovilia** [comment] 2018-01-12 06:45
@palmerye Hi, ECharts 4.0 will be release in 16th Jan. 
The implement method of Heatmap is strongly related to Canvas, which we currently cannot find a way to replace with SVG. So I'm afraid it will not be available in 4.0.

Note that [this kind of heatmap](http://gallery.echartsjs.com/editor.html?c=heatmap-cartesian) is supported for SVG, but not [those with blending effect](http://gallery.echartsjs.com/editor.html?c=xryt_4aNpe).

**Comment by palmerye** [comment] 2018-01-16 01:44
Thanks @Ovilia !

**Comment by chfw** [comment] 2018-03-25 20:56
Hei I got this in my notebook too. But after I restarted jupyter and reran the notebook, the warnings are gone. So I was not able to reproduce it later.

https://github.com/pyecharts/pyecharts/issues/430

**Comment by rafinkanisa** [comment] 2018-03-25 21:52
@chfw really? but in my case, I still cannot get rid of it... I have tried to produce other bar graph type and when I show the label on it, it still shows the error.

btw, other bugs I've spotted :
I wanted to produce a stacked bar chart like this one :
![image](https://user-images.githubusercontent.com/28089698/37880284-fd025e1e-30af-11e8-9e41-9f08f6d4cfa0.png)

but, when I change the type of yAxis to 'log', it cannot produce the graphs and shows error :
![image](https://user-images.githubusercontent.com/28089698/37880289-0b338418-30b0-11e8-951f-e2d75d54b545.png)

![image](https://user-images.githubusercontent.com/28089698/37880291-13976958-30b0-11e8-9bbe-c65f68a9b6eb.png)

and of course, when I try to put the label inside of every single bar it still shows the error I mention above.
Thank you for hearing me out.

**Comment by rafinkanisa** [comment] 2018-03-27 04:21
Hi! I wanted to report another bug I've found.

I have a graph like below. Everything works perfectly when I used 'canvas' renderer.
![image](https://user-images.githubusercontent.com/28089698/37946465-ab9e313c-31af-11e8-99dd-788198c0c0fd.png)

and this one is a screenshot when I use the magicType tools.
![image](https://user-images.githubusercontent.com/28089698/37946494-d6c5e2ba-31af-11e8-8019-aa8d367ca721.png)

But when I use 'svg' renderer, I cannot change the bar graph into line graph and shows error like picture below.
![image](https://user-images.githubusercontent.com/28089698/37946502-e4450d76-31af-11e8-8661-c794a58fef82.png)

![image](https://user-images.githubusercontent.com/28089698/37946517-f778f7b8-31af-11e8-9d3e-cab87bb2e985.png)

and I also notice that when I hover to the magicType tools, the 'title' text that should have appear below the icon goes to the edge on the top left of the graph. 
![image](https://user-images.githubusercontent.com/28089698/37946668-c90b30b6-31b0-11e8-820e-e22d491f16bf.png)

Hope it can be fixed on the next version because I really love this chart. Thank you and keep up the good work!

**Comment by Ovilia** [comment] 2018-03-27 10:54
@rafinkanisa Can you provide the code to reproduce it? Since I cannot reproduce it from a random chart.

**Comment by rafinkanisa** [comment] 2018-03-27 11:40
@Ovilia Sure! Here are the codes. I put 3 files corresponding with the error I mention above.

[Error Echarts.zip](https://github.com/ecomfe/echarts/files/1851777/Error.Echarts.zip)

**Comment by Ovilia** [comment] 2018-03-28 04:01
@rafinkanisa I fixed this problem in https://github.com/ecomfe/zrender/commit/be3fb89d6079f216d0779adf8378534ba715d175 .
Please wait for the next release, or you may build echarts by yourself.

To build:
1. clone echarts project
2. run `npm i`
3. run `node build/build.js --release`

Full tutorial: https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#Create%20Custom%20Build%20of%20ECharts

**Comment by rafinkanisa** [comment] 2018-03-28 04:07
@Ovilia Wow. Thank you...

**Comment by rafinkanisa** [comment] 2018-04-05 03:16
Hi! I've found another issue...

In my project I used 'canvas' renderer to create a graph on RTL mode and it's work fine like this :
![image](https://user-images.githubusercontent.com/28089698/38345411-3ac4652e-38b9-11e8-9f2c-cf643b355415.png)

![image](https://user-images.githubusercontent.com/28089698/38345452-7c95daa0-38b9-11e8-9ea9-dd01c7a5ab2a.png)


But, when I used 'svg' renderer, it becomes like this :
![image](https://user-images.githubusercontent.com/28089698/38345429-5a8ddca0-38b9-11e8-96e1-0bd5aa79a0dd.png)

![image](https://user-images.githubusercontent.com/28089698/38345460-88eb6acc-38b9-11e8-9d41-d35f3d86f16f.png)


Here, I put the codes to generate those graphs.
[errorRTL.html.zip](https://github.com/apache/incubator-echarts/files/1878458/errorRTL.html.zip)

Is this issue also part of the issue I mention before? Thank you...

**Comment by amalimdad** [comment] 2020-02-11 12:12
hello @Ovilia ,
I'm using echart and I want to getSVG of charts to draw pdf without rendering svg  in a web view , is there any function for that ?
because these a problem in bar charts after rendering it into web view and send the DOM elements to draw the pdf, it draws with no bars 
<img width="668" alt="Screen Shot 2020-02-11 at 3 11 18 PM" src="https://user-images.githubusercontent.com/38695840/74235762-c9c90080-4ce0-11ea-8403-903b83290ca9.png">

**Comment by nhaberl** [comment] 2020-08-03 14:00
Any news about rendering / export as svg ?

**Comment by Ovilia** [comment] 2022-01-12 08:25
SVG rendering should work almost the same as canvas by now. I'm going to close this issue. For new bugs report, please open new issues.

**Closed by Ovilia** 2022-01-12 08:25 UTC
Labels: bug, SVG, priority: high
