### ISSUE TITLE
[Feature] tree series nodeClick support clicking

### ISSUE THREAD

**Issue by tomatosqq** [apache/echarts#16170] opened 2021-12-04 07:17 UTC
### Version

5.2.2

### Steps To Reproduce
```ts
const data = {
        name: "设备一",
        children: [
          {
            name: "设备一",
            children: [
              {
                name: "设备一",
                children: [
                  { name: "设备一", value: 721 },
                  { name: "设备一", value: 4294 },
                ],
              },
              {
                name: "设备一",
                value: 3322,
              },
            ],
          },
          {
            name: "设备一",
            children: [
              { name: "设备一", value: 1616 },
              { name: "设备一", value: 1027 },
              {
                name: "设备一",
                children: [
                  { name: "设备一", value: 593 },
                  { name: "设备一", value: 330 },
                  { name: "设备一", value: 287 },
                ],
              },
              { name: "设备一", value: 843 },
            ],
          },
          {
            name: "设备一",
            children: [
              { name: "设备一", value: 2105 },
              { name: "设备一", value: 1316 },
              { name: "设备一", value: 3151 },
              { name: "设备一", id: 9, value: 5833 },
            ],
          },
        ],
      };
      let option = {
        tooltip: {
          trigger: "item",
          triggerOn: "mousemove",
        },
        series: [
          {
            type: "tree",
            id: 0,
            name: "tree1",
            data: [data],
            top: "10%",
            left: "8%",
            bottom: "22%",
            right: "20%",
            symbolSize: 10,
            edgeShape: "curve",
            edgeForkPosition: "63%",
            initialTreeDepth: 3,
            selectedMode: false,
            lineStyle: {
              width: 2,
              color: "#000",
            },
            itemStyle: {
              color: "blue",
            },
            label: {
              backgroundColor: "#fff",
              borderWidth: 1,
              borderColor: "green",
              borderRadius: 2,
              padding: [3, 5],
              color: "green",
              position: "right",
              verticalAlign: "middle",
              align: "left",
              fontSize: 14,
            },
            leaves: {
              label: {
                position: "right",
                verticalAlign: "middle",
                align: "left",
              },
            },
            emphasis: {
              focus: "series",
            },
            expandAndCollapse: true,
            animationDuration: 550,
            animationDurationUpdate: 750,
          },
        ],
      };
      this.dom = echarts.init(this.$refs.dom, "tdTheme");
      this.dom.setOption(option);
      this.dom.on(
        "click",
        function (param) {
          console.log(param);
          if (!param.event.target.culling) {
            console.log("点文字");
          } else {
            console.log("icon");
          }
        },
        false
      );
```
### Current Behavior

点击树状图的symbol和label效果相同 无法达到分离 

### Expected Behavior

希望点击label能获取节点信息但是不要收起或者展开子节点 点击symbol可以收起或展开子节点

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment] 2021-12-14 03:26
It should provide a `nodeClick` option with values of `false | 'expand' | 'link'` similar to [treemap series](https://echarts.apache.org/en/option.html#series-treemap.nodeClick).

**Comment by Ovilia** [comment] 2021-12-14 03:29
Duplicate of #16169. Please update your issue rather than open a new one next time. Thanks!

**Closed by Ovilia** 2021-12-14 03:29 UTC
Labels: new-feature, duplicate, topic: tree, difficulty: easy
