### ISSUE TITLE
Overlapping Links in Graph

### ISSUE THREAD

**Issue by dangoldstein** [apache/echarts#11260] opened 2019-09-17 08:01 UTC
### Version
4.2.0-rc.2

### Steps to reproduce
1. Open the following example:
https://www.echartsjs.com/examples/en/editor.html?c=graph-simple

2. Add to the array of links another link that already exists (so that there will be two links connecting the same two nodes)
For example: 
```
{
    source: '节点1',
    target: '节点3'
}
```

### What is expected?
Two links will be connecting the two nodes.

### What is actually happening?
Only one link is rendered.

**Comment by Ovilia** [comment] 2019-09-18 02:28
Duplicate of #11260

**Comment by dangoldstein** [comment] 2019-09-19 10:53
> Duplicate of #11260

You referenced this issue ..

**Comment by Ovilia** [comment] 2019-09-23 07:22
Sorry... I made a mistake. I was referencing #10813 perhaps.
Now I'll mark #10813 to be a duplicate of this issue because this one is in English.

**Comment by deqingli** [comment] 2019-11-15 13:41
The strategy I used in the demo:

+ If the `edges` is an odd number, the curveness of the line starts from 0 and the step is 0.2, for example `[0, 0.2, -0.2, 0.4, -0.4, 0.6, -0.6]`, start from 0 in order to make the line in the center is a straight line.
![image](https://user-images.githubusercontent.com/13548221/68947051-733a4c00-07ef-11ea-842e-a8a5990477c4.png)
 
+ If the `edges` is an even number, the curveness of the line starts from 0.1 and the step is 0.2, for example `[0.1, -0.1, 0.3, -0.3, 0.5, -0.5]`, starts from 0.1 and -0.1 in order to keep the gap of the center is also 0.2, see the following picture, see the following picture:
![image](https://user-images.githubusercontent.com/13548221/68946751-b3e59580-07ee-11ea-843f-0c0c6d86451a.png)

+ If there are only two edges, the curveness of the line is `[0.17, -0.17]`, only want to make the step much bigger.

I think we should provide a way for user to set the `step`  of the curveness. @100pah @pissang  do you have any idea about how to set the configuration items？

**Comment by pissang** [comment] 2019-11-19 07:21
I prever still using current `curveness` property. 

If we have multiple edges, we can do linear interpolation between [0, curveness] for each edge.

**Comment by deqingli** [comment] 2019-11-19 08:07
I think this way maybe work, `step` can be implicitly derived by the range, but I prefer the range should be [-curveness, curveness] to keep symmetry.

**Comment by pissang** [comment] 2019-11-19 10:52
@deqingli You are right, it should be [-curveness, curveness]

**Comment by 100pah** [comment] 2019-11-19 11:27
@pissang If only interpolating in `[0, curveness]`, I am worried about this case:

If there are both the case that 2 or 3 edges in a pair of nodes and many edges (e.g., more than 6) in a pair of nodes in a single graph, how can a user set curveness to make them both look pretty?

Probably we should better provide a more wise strategy, by which users do not need to set curveness for each edges according to each degree?

**Comment by pissang** [comment] 2019-11-19 11:33
@100pah Do you have any suggestions

**Comment by dangoldstein** [comment] 2020-01-08 11:22
Hey everyone,
Any updates on this issue?
Thank you

**Comment by meinac** [comment] 2020-03-21 00:32
Hi, I was looking for the same feature until I found this issue. What about starting with a simple approach which allows users to be able to set the `curveness` at least manually, until you find a nice algorithm to set the `curveness` automatically?

Also there is another issue that if you want to add a loop edge(an edge which has the source and the target nodes are the same) it does not show it at all.

**Comment by raray** [comment] 2020-05-05 15:58
@deqingli How did you get multiple edges with the same source/target to render in the first place?

**Comment by stolenfather** [comment] 2020-05-06 10:54
Hey everyone,
Any updates on this issue?
Thank you

**Comment by ohadleshno** [comment] 2020-05-15 05:49
Is there a solution to the problem?

**Comment by maxyuan8** [comment] 2020-08-20 02:40
v4.8.0 好像还是没有解决这个问题

**Comment by wf123537200** [comment] 2020-08-20 03:20
[feat 12590](https://github.com/apache/incubator-echarts/pull/12590) solution this, supported in v4.9.0

**Closed** 2021-07-14 01:32 UTC
Labels: en, new-feature, priority: high, topic: graph, waiting-for: community
