### ISSUE TITLE
Toggle web charts to hide problems

### ISSUE THREAD

**Issue by rzqs** [apache/echarts#19962] opened 2024-05-21 09:33 UTC
### Version

5.4.3

### Link to Minimal Reproduction

echarts initializes, goes to other web pages, comes back after a while, and disappears

### Steps to Reproduce

echarts.init();echarts initializes, goes to other pages, comes back after a while, disappears, and resize is useless

### Current Behavior

I initialize a line chart, run the project, then go to other web pages, and when I go back to my project, the echarts are hidden, the mouse is displayed, the mouse is not hidden, and the dom is always present, and the dom elements can be detected

### Expected Behavior

 document.addEventListener('visibilitychange', function () {
        myChart.resize()
      });

**Comment by plainheart** [comment] 2024-05-21 13:41
Duplicate of #19946

**Closed by plainheart** 2024-05-21 13:41 UTC
Labels: bug, pending, duplicate, en
