### ISSUE TITLE
[Bug] CSS zoom scaling causes tooltip misalignment

### ISSUE THREAD

**Issue by zystudios** [apache/echarts#20095] opened 2024-06-28 09:08 UTC
### Version

latest

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-stack

### Steps to Reproduce

![image](https://github.com/apache/echarts/assets/29728228/5cfcfda8-0c37-4f3e-8685-93602f96c93e)

![image](https://github.com/apache/echarts/assets/29728228/3d7139e6-66df-40fc-999b-0d350f5bfbb4)

If the parent container of the echarts has zoom scaling, the tooltip and mouseover of all charts are misaligned.

### Current Behavior

If the parent container of the echarts has zoom scaling, the tooltip and mouseover of all charts are misaligned.

### Expected Behavior

If zoom scaling exists in the parent container of the echarts, don't misalign the tooltip and mouseover of all charts

### Environment

```markdown
- OS: mac/win
- Browser: chrome
- Framework:react, vue
```

**Comment by plainheart** [comment] 2024-06-28 09:23
Duplicate of #15103

**Closed by plainheart** 2024-06-28 09:23 UTC
Labels: bug, pending, duplicate, en
