### ISSUE TITLE
[Bug] Axis.nameTextStyle.overflow 不生效

### ISSUE THREAD

**Issue by LiDopamine** [apache/echarts#19489] opened 2024-01-09 11:48 UTC
### Version

main

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2Srz8sNCMALbeWBwcjOQAFACMAAzJAJQAdABmEP7-8bT-MKwAtCwYYLSZAFbAENAFACRVjqRhkQAywEyQMEQAROEQAgL-VP2t6O1UclQVJhRjBO4esADuw2DaRCnJk6TaVBCs2mA7qfvowD5UHFlFawMARhxUjADWEyHoT4z076wOMBLAIAMLAIocOgAYgAzPDaCE7PZWnhbhAqIRYKIQisPEIwCJsYkAKx7WAAJlh5IpFIALDxKYkAByMxKwklsukAdkZFIAbMlrJdPNQ6P56sokSRbHYANxAA

### Steps to Reproduce

无

### Current Behavior

轴标题应该按照 overflow 的标记折行，目前未折行，并且宽度设置也未生效

### Expected Behavior

轴标题折行，并且宽度设置生效

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment] 2024-01-09 17:33
duplicate of #16940, #18408, etc.
📌 Please search existing issues before submitting a new one.

**Comment by LiDopamine** [comment] 2024-01-10 14:22
Thank you for your response.
I am willing to assist in fixing this issue. Before proceeding, we need to confirm whether we should continue using the undocumented attribute **nameTruncate** to limit axis names, or use **nameTextStyle** as mentioned in the document to achieve the same functionality.

**Comment by Ovilia** [comment] 2024-01-16 10:09
@LiDopamine  This should be a document problem (missing `nameTruncate`). I will make a pull request to the doc later.

**Comment by Ovilia** [comment] 2024-01-16 10:22
Fixed in https://github.com/apache/echarts-doc/commit/0d22eaa136bf6c06486ec9a8910f12f27306d69c

**Closed by Ovilia** 2024-01-16 10:22 UTC
Labels: bug, pending
