### ISSUE TITLE
[Bug] Switching magicType feature requires a second attempt

### ISSUE THREAD

**Issue by mityaua** [apache/echarts#20371] opened 2024-09-24 12:25 UTC
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-marker&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQAqOAtiDgE4CGYArkzrAMIAWLaAHNuEOGD7cewOmKGwA6jhwBrSkQC-AGiJhgwLJBAFUxDEwhCRTKi1IQAzuvTaiuEdAAmJ1-j0GAI2BSEyJ0Bz5gAHcCMCZ2HB0zADMcNk58QjN0OhYhCABjagBPRhMMUsyAbUoHMBYCtQBdWF9iDU0k2FIAQXsHULMwSqoCthwhYCZiyi70IPYvFmmAcRZjWGSWLAdEsNhPNhYCGoBZGFnYGgTLyiVPW-o-dluAMQtbgGU2L8XKJs6RGKfUcg2IwzKVwAbtsbnNYHZHAAZFgBHBYMEpKa5MBgZhUJAwrAJDSwAANPGc7UB4WYEBwA1gVX2pmy0BYdEylAAEpZJHVZvs_CMrlgxDhBdlYHUGioCAAiajAepYeXw9CHeonACMAAYtLBtdqDdqAMwm42GgBMJptsAAnE14W10KyzOzOVQkdEGWBJdkIVyxdAJerpfVGgqlSq1UKDkcdQaALR2u0AVgN5tgdt1Tv2HXQAI0AG4gA

### Steps to Reproduce

1. Open the link.
2. Click on the "stack" icon.
3. Click on the "stack" icon again.

### Current Behavior

Chart view is changing after the second click (fon first try).

### Expected Behavior

Chart view is changing after the first click (with initial stack: "Total" or etc).

### Environment

```markdown
- OS:Windows 11
- Browser: Version 129.0.6668.59 (Official Build) (64-bit)
- Framework: Vue@3
```

**Comment by helgasoft** [comment] 2024-09-24 20:40
duplicate of #16473, see also #19131
Workaround - remove _stack_ from series.

**Comment by mityaua** [comment] 2024-09-25 06:24
> duplicate of #16473, see also #19131 Workaround - remove _stack_ from series.

Hmm, but what if I don't want to remove the stack? I need a default view with the stack. 

For example - I have a lot of data and initial view without stack looks not so good. 
![image](https://github.com/user-attachments/assets/05e6ff4a-1f44-496b-94cd-d43d69fb7a4b)
So better to show a "stacked" view with the magicType button.
![image](https://github.com/user-attachments/assets/3cbcb760-d370-42f6-a6a0-9ef240198b62)

**Comment by MatthiasMert** [comment] 2024-09-25 07:23
You can implement the stack behaviour as [user-defined tool](https://echarts.apache.org/en/option.html#toolbox.feature) if neccessary.

[Example](https://echarts.apache.org/examples/en/editor.html?c=line-marker&code=DYUwLgBAzmCGDGBrEATCBeCYBOBXEA3AFBED2ADmAJakB2GEA3kRFlWKAFxMutYgAPMNwDkAFRABbciGywwubCAgBhABaxaAc2VV6YNcpWlJerRADqIEIhG8AvgBpeYUqWDVy3ZnyzYqWjrYorACVFB2rE68oDq0KN7RrK7uAEakAt68rFBqpADu3Dj4zr4AZiDyiiBZvqySAJ4AynBItXXJ7FzQrchoAPwQIgCqtDAIthCiLRMipR0QVPB0ogCyABwAdABMjgDMWwAswAC0R46HmwCMwHsADJsAbI5XAKybewAyj3cX25uvU5bK4nS43E7bK4Al5XT5bXYHTaHABeEFWryhAE59ncgdcLjtTlc9kjHI9NpiiSTMSdyZi4TscXjDgTtsBzpc2dt_rsrjdIQCTnz2ddQTtPhiKTjUeisY4BQB2PFXVmfPbvBVMk7vPbyzbrT7bS7Y-7MsXgrZ7MVss6kzkMhG4y2s4DEqV010kw60ikikGcv3miVyxXI1b3Uk8z4nB68hUAkUssEi3UBjmE96vPVKnUQzZK4HWwNp0VgtUPFk85FzbJ1OjwYBLRDcMq4Wjwah0CAACgAlDwFnxxkhUAwAITDvrEQesZZjSBQWRUEBQADylBo9EwjXUsGwYE2AH1JKQUCBgJsKJ3aJtF_4V5tJLByN278uoBgAHxMJQKbD0RhJ24SdR0GcRSDgYARCmCA2zPMo9FQex7F7acZznGAsDcYB0gEddrwYRgKiqJRvAgRoZjaJg2A4GoegmUChlGSdoOmXo5kWOcWgabpGHSbAz2wYxgFIYJ6JHAYhgAYj2ABRTF1hUV5WOkx41JEZDkLQwcdw0fdb3AfDN27QClxXYCzLXDc6EcLC0gyIpsNwoy6BQ7S6iSBYljobjeP4wThNE4DekYkQZPkxTlJgsK1MeDTayiWt7AceYBAAQTCKB2mSBoZFEeB5BALRRIaGtfHSOC9waABxZ8W1gYBF3mVgUHkWBuAAbREVY6A48R8D6qwUD6sQ1FwPqADF_D6pp5BmtsRAAXRS3gGgy8JsqwXK6JEAA3BqBuaiBQnCT5YFSc9NtYMpRKfMAwFkURGH24B8HsCAAAaVEiPhkqieY33MiAOtrHw6loWBJB2gAJAJDBgMq6jAbbREbWgQER3wgIgAAiMQIIanGjpatrOquX4ID5WziWplVKd2enbMxRajs81gwd8CGodET4ChXMBMb4ZG8qGNGMeJ8Tm1x_HIKJhKIFauAydsiFbIZrMIF1CAGbuFmkt4Zb7AIIA)

**Comment by mityaua** [comment] 2024-09-25 07:54
> You can implement the stack behaviour as [user-defined tool](https://echarts.apache.org/en/option.html#toolbox.feature) if neccessary.
> 
> [Example](https://echarts.apache.org/examples/en/editor.html?c=line-marker&code=DYUwLgBAzmCGDGBrEATCBeCYBOBXEA3AFBED2ADmAJakB2GEA3kRFlWKAFxMutYgAPMNwDkAFRABbciGywwubCAgBhABaxaAc2VV6YNcpWlJerRADqIEIhG8AvgBpeYUqWDVy3ZnyzYqWjrYorACVFB2rE68oDq0KN7RrK7uAEakAt68rFBqpADu3Dj4zr4AZiDyiiBZvqySAJ4AynBItXXJ7FzQrchoAPwQIgCqtDAIthCiLRMipR0QVPB0ogCyABwAdABMjgDMWwAswAC0R46HmwCMwHsADJsAbI5XAKybewAyj3cX25uvU5bK4nS43E7bK4Al5XT5bXYHTaHABeEFWryhAE59ncgdcLjtTlc9kjHI9NpiiSTMSdyZi4TscXjDgTtsBzpc2dt_rsrjdIQCTnz2ddQTtPhiKTjUeisY4BQB2PFXVmfPbvBVMk7vPbyzbrT7bS7Y-7MsXgrZ7MVss6kzkMhG4y2s4DEqV010kw60ikikGcv3miVyxXI1b3Uk8z4nB68hUAkUssEi3UBjmE96vPVKnUQzZK4HWwNp0VgtUPFk85FzbJ1OjwYBLRDcMq4Wjwah0CAACgAlDwFnxxkhUAwAITDvrEQesZZjSBQWRUEBQADylBo9EwjXUsGwYE2AH1JKQUCBgJsKJ3aJtF_4V5tJLByN278uoBgAHxMJQKbD0RhJ24SdR0GcRSDgYARCmCA2zPMo9FQex7F7acZznGAsDcYB0gEddrwYRgKiqJRvAgRoZjaJg2A4GoegmUChlGSdoOmXo5kWOcWgabpGHSbAz2wYxgFIYJ6JHAYhgAYj2ABRTF1hUV5WOkx41JEZDkLQwcdw0fdb3AfDN27QClxXYCzLXDc6EcLC0gyIpsNwoy6BQ7S6iSBYljobjeP4wThNE4DekYkQZPkxTlJgsK1MeDTayiWt7AceYBAAQTCKB2mSBoZFEeB5BALRRIaGtfHSOC9waABxZ8W1gYBF3mVgUHkWBuAAbREVY6A48R8D6qwUD6sQ1FwPqADF_D6pp5BmtsRAAXRS3gGgy8JsqwXK6JEAA3BqBuaiBQnCT5YFSc9NtYMpRKfMAwFkURGH24B8HsCAAAaVEiPhkqieY33MiAOtrHw6loWBJB2gAJAJDBgMq6jAbbREbWgQER3wgPEvoIDAsQIIalS4JABD0ZQI6Wrazqrl-CA-Vs4lGZVendlZ2zMUWo7PNYMHfAhqHRE-AoVzATG-GRvKhjRjHKZx4KGMk8DIOJ-JScQimEogVq4Bp2yIVstmswgXUIDZu4uaS3hlvsAggA)

Awesome. Thx a lot.

**Closed** 2024-09-25 08:02 UTC
Labels: bug, pending, en
