### ISSUE TITLE
On clicking treemap block , its get moved to right.

### ISSUE THREAD

**Issue by Monali-ITT** [apache/echarts#15531] opened 2021-08-13 13:32 UTC
### Version
4.4.2

### Steps to reproduce
Execute treemap
Output get displayed.
Click on any block , output get moved to right.

### What is expected?
It should not move treemap output to right.

### What is actually happening?
Its moving treemap output to right.

---
https://echarts.apache.org/examples/en/editor.html?c=treemap-disk

**Comment by susiwen8** [comment] 2021-08-13 14:08
Well, This not a bug.  It' moving to the center of canvas.

**Closed by susiwen8** 2021-08-13 14:08 UTC
Labels: bug, en
