### ISSUE TITLE
How can I make a violin plot in ECharts?

### ISSUE THREAD

**Issue by frankyaorenjie** [apache/echarts#11820] opened 2019-12-10 06:42 UTC
### What problem does this feature solve?
Violin plot is very useful. Example here: https://seaborn.pydata.org/generated/seaborn.violinplot.html

### What does the proposed API look like?
I don't know the API, but I want the feature.

**Comment by MohammedAlSafwan** [comment] 2020-01-29 13:57
Any news on this feature ?

**Comment by bkmgit** [comment] 2020-02-01 05:09
A few examples at:

* http://bl.ocks.org/z-m-k/5014368 (no license)
* https://plot.ly/javascript/violin/
* https://github.com/datavisyn/chartjs-chart-box-and-violin-plot

Would this be better as a module or within the main library?

**Comment by Ovilia** [comment] 2020-02-01 05:47
ECharts have many chart types now and we are more cautious when considering adding new chart types because it adds to the package size and we need to consider if this chart type is frequently used enough.

For your case, I'd suggest implementing it using the custom series mechanism by yourself.
The document is https://echarts.apache.org/en/option.html#series-custom . The examples and API documents should be enough for you to create by yourself, but you do need spend some time understand it.
If you think there are some extra API needed when you use the custom series, do let me know.

**Comment by frankyaorenjie** [comment] 2020-02-12 11:55
Thanks @bkmgit and @Ovilia

**Comment by Kittywyk** [comment] 2021-09-09 08:44
> Thanks @bkmgit and @Ovilia

Hi, @frankyaorenjie. 
I also have to use echarts to plot violin plots.  I'm a newbie, though I've already read the document of custom series mechanism, I still didn't have an idea on how to plot it. 
If you plotted it successfully, could u pls give me some advice and guidance? 
Thanks a million!

**Comment by Ovilia** [comment] 2021-09-10 06:39
@Kittywyk Hi, you make checkout these similar examples:

- https://echarts.apache.org/examples/en/editor.html?c=cycle-plot
- https://echarts.apache.org/examples/en/editor.html?c=custom-profit
- https://echarts.apache.org/examples/en/editor.html?c=custom-error-bar

The only difference is the shape. You may probably use [bezierCurve](https://echarts.apache.org/en/option.html#series-custom.renderItem.return_bezierCurve) to draw the shape. As for how to implement the violin shape with bezier curves, you may refer to online resources or the chart implementations as mentioned above.

**Comment by Kittywyk** [comment] 2021-09-10 06:42
> @Kittywyk Hi, you make checkout these similar examples:
> 
> * https://echarts.apache.org/examples/en/editor.html?c=cycle-plot
> * https://echarts.apache.org/examples/en/editor.html?c=custom-profit
> * https://echarts.apache.org/examples/en/editor.html?c=custom-error-bar
> 
> The only difference is the shape. You may probably use [bezierCurve](https://echarts.apache.org/en/option.html#series-custom.renderItem.return_bezierCurve) to draw the shape. As for how to implement the violin shape with bezier curves, you may refer to online resources or the chart implementations as mentioned above.

Thank you very much. I'll have a try.

**Comment by Ovilia** [comment] 2021-09-10 06:54
Update: It should be polygon + smooth instead of bezierCurve because the later cannot be multiple curves.

**Comment by wangjiawen2013** [comment] 2024-01-05 01:58
Violinplot, errorbar are widely used and have already been used for many years in scientific community. It seems that they are becoming more and more popular in recently years. Hope you can add them to echarts. Vega-lite and plotly support violinplot and errorbar now. A lot of users of echarts are lack of the skill to customize a new series, So hope you can support these plots.

**Comment by wangjiawen2013** [comment] 2024-01-05 02:04
Matplotlib and seaborn also support violinplot and errorbar, both of them are absolutely frequently used.

**Comment by baiyuhong** [comment] 2024-02-17 12:11
violinplot 用到小提琴样式但是没有，又不想再引入别的框架，只能自定义了，不知哪位大神已经造了轮子，能否提供帮助

**Comment by plainheart** [comment] 2024-02-18 00:15
Duplicate of #18878

**Closed** 2024-02-18 00:15 UTC
Labels: new-feature, en

**Comment by septatrix** [comment] 2024-06-06 23:28
It would have been better to merge the newer issue into this older one as this already has 10 upvotes and likely more people are subscribed here than in the new issue...

**Comment by cgcdev0512** [comment] 2025-04-06 19:33
Now can we use violin plot in echart without customization?
