### ISSUE TITLE
[Bug] grid 多图表 显示位置异常

### ISSUE THREAD

**Issue by dontworrywearetogether** [apache/echarts#18854] opened 2023-07-06 03:28 UTC
### Version

5.4

### Link to Minimal Reproduction

https://codesandbox.io/embed/basic-line-chart-forked-7mfz5h?fontsize=14&hidenavigation=1&theme=dark

### Steps to Reproduce

图表是 一个 line 和 一个 pie
但是 pie的位置总是 不对

grid 的 代码是这个样子的:

'''
  const media = [
    {
      option: {
        grid: [
          {left: "10%",right: "50%",width: "50%",top: "10%",bottom: "10%"},
          { left: "50%", right: "10%", width: "50%", top: "10%", bottom: "10%" }
        ]
      }
    },
    {
      query: {
        maxWidth: 768
      },
      option: {
        grid: [
          {left: "10%",right: "10%",top: "10%",bottom: "50%",width: "20%"},
          { left: "10%", right: "10%", top: "50%", bottom: "10%", width: "20%" }
        ]
      }
    }
  ];

  myChart.setOption({
    option,
    media
  });
'''

### Current Behavior
![微信截图_20230706112928](https://github.com/apache/echarts/assets/73633325/020e07fa-5936-4966-896c-bf5e7fc134a9)

### Expected Behavior

line 和 pie 分别占据图表左右两侧

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment] 2023-07-06 04:15
Duplicate of #18840

**Closed by plainheart** 2023-07-06 04:16 UTC
Labels: bug, pending, duplicate
