### ISSUE TITLE
Legend Rendering

### ISSUE THREAD

**Issue by GGupzHH** [apache/echarts#14153] opened 2021-01-29 09:17 UTC
### Version
4.9.0

### Reproduction link
[https://codepen.io/ggupzhh/pen/MWbWjjK](https://codepen.io/ggupzhh/pen/MWbWjjK)

### Steps to reproduce
When using SVG to render the chart, Legend mode is scroll, and legend displays exception

当使用SVG 渲染图表 ，legend 图例模式为scroll  ，legend显示异常

### What is expected?
When using SVG to render the chart, Legend mode is scroll, and legend displays exception

当使用SVG 渲染图表 ，legend 图例模式为scroll  ，legend显示异常

### What is actually happening?
When using SVG to render the chart, Legend mode is scroll, and legend displays exception

当使用SVG 渲染图表 ，legend 图例模式为scroll  ，legend显示异常

---
When using SVG to render the chart, Legend mode is scroll, and legend displays exception

当使用SVG 渲染图表 ，legend 图例模式为scroll  ，legend显示异常

**Comment by Ovilia** [comment] 2021-01-29 09:46
Try with 5.0 version. I cannot reproduce it.

**Comment by GGupzHH** [comment] 2021-01-29 10:16
5.0 is fine, 4.9 is not

This is the flawed demo of 4.9
https://codepen.io/ggupzhh/pen/MWbWjjK

**Comment by Ovilia** [comment] 2021-02-01 02:12
Yes. So please upgrade to 5.0. It is not planned to be fixed in 4.x.

**Comment by GGupzHH** [comment] 2021-02-01 02:18
okk

**Closed** 2021-02-01 02:38 UTC
Labels: SVG, bug, cannot-reproduce, pending, waiting-for: community
