### ISSUE TITLE
数据跨度较大时，堆叠柱状图的使用

### ISSUE THREAD

**Issue by lightersss** [apache/echarts#18330] opened 2023-03-04 10:17 UTC
### What problem does this feature solve?

https://codesandbox.io/s/dataset-in-object-array-forked-3d55ks?file=/index.js
你好，我现在想使用堆叠柱状图，但是由于数据跨度较大，我选择使用了log轴，并且将较小的值放在底部，也就是对应dataset中的dimensions靠前的字段，但是效果却是部分的轴出现了悬空。请问这种数据跨度较大情况下的堆叠柱状图有比较好的实现方式吗，谢谢

### What does the proposed API look like?

每一列的柱状图只显示source中包含的字段，从0开始。并且每一列自下而上的顺序可以自定义，或者按照dimensions的顺序。

**Comment by helgasoft** [comment] 2023-03-04 18:14
Unfortunately one cannot use stacked bars with **log** scale.  Stacked bars are all about **proportions** between the parts and with a log scale those proportions are distorted. See this [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeBYAULWAbApgcx2gBMAuZAXwBp1MxhgtIQykqbYiBDMTgZxzAt2mIhAC2hXlGi8yAbQBEIAE7AiAVwDGYBZVgKATAAYAjAFZd-4yYBslw6YDsCgLp7hsXsHXLNOeR6YSLAqalqC-gCy3JoAFpywADLcYDiW1mZkxkZGetY2WTl5TmQmOTlUsIHIIaoa2mQKkRBYANawACo4nOmmmbBl5cW2hUWw1o6jRrBsGJjzqHPz86H1EQoAwrE4OPywG8CawD3US8vjfWQAHDYAdAAsp-fz-WQ2ZrcGT88XJpOwVwMtzM32Ws2eix-tTCDX0AHVOFhoOowLAAEKqADu0AgaVB5wyZEcQMe1Uwr1gZgAzLcAJz45YTMhU2m3EwMmYeFzscGwAAeAEE-RBZDUwABPED-fSabj4YDKcUKGbfcVCkUsWASqWNLDAPCWMScPkkKnlaa8_jKXGiuQeYLa6UKABGnGUll4PE0rUadB4WGVvKCWslTtd7r0ns43t9wH9gfxDtDjXDHq9Pv0fsRCfY3LQ5AA3EA)
In _Macha Latte_ 2017 (yellow) and _Milk Tea_ 2015 (blue) values are identical (10,000), but their sizes looks very different just because they are in different data columns.
![image](https://user-images.githubusercontent.com/13038071/222922139-1c58cd43-7400-4e21-b0a5-699f905dddb9.png)

**Comment by lightersss** [comment] 2023-03-05 02:37
> Unfortunately one cannot use stacked bars with **log** scale.  Stacked bars are all about **proportions** between the parts and with a log scale those proportions are distorted. See this [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeBYAULWAbApgcx2gBMAuZAXwBp1MxhgtIQykqbYiBDMTgZxzAt2mIhAC2hXlGi8yAbQBEIAE7AiAVwDGYBZVgKATAAYAjAFZd-4yYBslw6YDsCgLp7hsXsHXLNOeR6YSLAqalqC-gCy3JoAFpywADLcYDiW1mZkxkZGetY2WTl5TmQmOTlUsIHIIaoa2mQKkRBYANawACo4nOmmmbBl5cW2hUWw1o6jRrBsGJjzqHPz86H1EQoAwrE4OPywG8CawD3US8vjfWQAHDYAdAAsp-fz-WQ2ZrcGT88XJpOwVwMtzM32Ws2eix-tTCDX0AHVOFhoOowLAAEKqADu0AgaVB5wyZEcQMe1Uwr1gZgAzLcAJz45YTMhU2m3EwMmYeFzscGwAAeAEE-RBZDUwABPED-fSabj4YDKcUKGbfcVCkUsWASqWNLDAPCWMScPkkKnlaa8_jKXGiuQeYLa6UKABGnGUll4PE0rUadB4WGVvKCWslTtd7r0ns43t9wH9gfxDtDjXDHq9Pv0fsRCfY3LQ5AA3EA)
> In _Macha Latte_ 2017 (yellow) and _Milk Tea_ 2015 (blue) values are identical (10,000), but their sizes looks very different just because they are in different data columns.
> ![image](https://user-images.githubusercontent.com/13038071/222922139-1c58cd43-7400-4e21-b0a5-699f905dddb9.png)
> 

Thank you. But is there a better solution to my problem? The data span in the stacked bar chart is large, resulting in a part of smaller data that cannot be well displayed

**Comment by helgasoft** [comment] 2023-03-05 02:47
two ideas:
- divide all large values by 1000 (and/or 10K, 100K, etc.) to make them comparable to the small ones. Then add **labels** like "x1000", "x10K", etc. to the corresponding bars. Or do the same but with a normal (non-stacked) bar chart.
- divide data by value into 2,3,etc. groups (if you can) and display in separate normal bar charts

**Comment by helgasoft** [comment] 2023-03-20 06:43
duplicate of #17960

**Comment by Ovilia** [comment] 2024-01-17 07:55
See conclusion at [#19234](https://github.com/apache/echarts/issues/19234#issuecomment-1776794193). Stacked bars using log axis is misleading and thus this problem is not going to be fixed.

**Closed by Ovilia** 2024-01-17 07:55 UTC
Labels: new-feature, pending
