### ISSUE TITLE
CSS Warning : " Expected color but found ‘null’/'none' " on Firefox

### ISSUE THREAD

**Issue by InakiUrrutia** [apache/echarts#15238] opened 2021-06-25 08:05 UTC
![Screenshot from 2021-06-25 09-54-35](https://user-images.githubusercontent.com/57755769/123392032-e5167200-d59c-11eb-82cb-41e5bdaf0913.png)
### Version
5.1.2

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=line-stack](https://echarts.apache.org/examples/en/editor.html?c=line-stack)

### Steps to reproduce
1- Open Firefox, Go to Echarts examples, find Stacked Line Chart.
2- Open web developper console.
3- Go to console Tab and then click on the 'CSS' filter to display CSS logs.
4- On the graph, over the graph to display the tooltip, the warnings should appaears on the console.

### What is expected?
No warnings

### What is actually happening?
CSS Warnings apparearing whenever i move the mouse with tooltip open:

Expected color but found ‘none’.
Expected color but found ‘null’.

**Comment by plainheart** [comment] 2021-06-26 00:37
It seems this warning information will still be thrown as long as the mouse hovers on the line series, even if no tooltip is specified.

**Comment by plainheart** [comment] 2021-06-26 02:07
Maybe it is caused by the invalid value `none`/`null` for canvas context.
This is just in the warning level, so I'm not sure if we need to fix it.
Related source code: https://github.com/ecomfe/zrender/blob/master/src/canvas/graphic.ts#L456-L470
@pissang Please take a look.

**Comment by pissang** [comment] 2021-06-26 02:18
@plainheart The warn seems annoying. I think it should be fixed.

**Comment by InakiUrrutia** [comment] 2021-07-05 10:23
The warning displays for literally hundreds of lines when loading the page,  and hovering the series keeps throwing them on and on.
I believe we can classify it in the annoying category

**Comment by pissang** [comment] 2021-07-05 14:15
@InakiUrrutia Yeah we will fix it ASAP

**Closed** 2021-07-15 10:17 UTC
Labels: bug, en

**Comment by lzpons** [comment] 2021-07-25 09:41
@pissang & the Echarts Team : thank you very much for having solved this issue, really appreciate.
