### ISSUE TITLE
[Bug] nameMap does not work with svg while using registerMap,geoJson works normal

### ISSUE THREAD

**Issue by falcon95** [apache/echarts#16979] opened 2022-05-04 15:05 UTC
### Version

5.3.2

### Steps to Reproduce

1. Open the demo, https://echarts.apache.org/examples/zh/editor.html?c=geo-beef-cuts
2. Add nameMap:{"Filet":"菲力牛排"} in series, it's not work
3. The demo https://echarts.apache.org/examples/zh/editor.html?c=map-HK works normal

### Current Behavior

 nameMap does not work with svg while using registerMap

### Expected Behavior

nameMap support svg

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment] 2022-06-05 12:57
Duplicate of #17156

**Closed by plainheart** 2022-06-05 12:57 UTC
Labels: bug, pending, duplicate, en, waiting-for: community
