### ISSUE TITLE
[Bug] BarMinHeight for Stack-Bars incorrectly overlaps bars

### ISSUE THREAD

**Issue by Arhimondear** [apache/echarts#18445] opened 2023-03-29 11:11 UTC
### Version

from 5.3.0

### Steps to Reproduce

Example: https://echarts.apache.org/examples/en/editor.html?c=bar-stack&version=5.4.2
1.On this example set data for "Email" to [20, 132, 101, 134, 90, 230, 210] and add BarMinHeight > 1
![image](https://user-images.githubusercontent.com/129281615/228512895-ef9bd14c-60c5-435d-b370-3ee3c2d00161.png)
2.Now, if you're hover over green bar on first stack-bars it will overlap yellow bar

### Current Behavior

Bars with BarMinHeight >1 dont take their all height and hiding behind other bar. This is visible if you point to green bar
![image](https://user-images.githubusercontent.com/129281615/228514655-87e98260-68f3-4693-ad90-2862ff61f572.png)

### Expected Behavior

Expected Behavior can see on versions below 5.3.0, for example on 5.2.2. In this case green bar take all min height
![image](https://user-images.githubusercontent.com/129281615/228515769-0080b155-ea86-4ccd-9f15-48c2aef8c666.png)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment] 2023-03-31 02:23
Duplicate of #16565

**Closed by Ovilia** 2023-03-31 02:23 UTC
Labels: bug, pending, duplicate, en
