### ISSUE TITLE
ThemeRiver series click has incorrect data

### ISSUE THREAD

**Issue by ataft** [apache/echarts#15759] opened 2021-09-20 20:44 UTC
### Version
5.2.0

### Reproduction link
[https://codepen.io/ataft/pen/rNwvvyv](https://codepen.io/ataft/pen/rNwvvyv)

### Steps to reproduce
https://codepen.io/ataft/pen/rNwvvyv

Click on any data point

### What is expected?
The param values should be the ones that were clicked on

### What is actually happening?
The param values are incorrect

**Comment by Ovilia** [comment] 2021-09-23 08:25
Duplicate of #13758. Please follow that issue. We will put it to a higher priority.

**Closed** 2021-09-23 08:26 UTC
Labels: bug, pending, duplicate, en
