### ISSUE TITLE
[Bug] [candlestick] Data points are not displayed

### ISSUE THREAD

**Issue by huogui** [apache/echarts#18156] opened 2023-01-10 02:18 UTC
### Version

5.2.1

### Steps to Reproduce

demo link:https://codesandbox.io/s/apache-echarts-demo-forked-047g0l?file=/index.js

### Current Behavior

demo link:https://codesandbox.io/s/apache-echarts-demo-forked-047g0l?file=/index.js

### Expected Behavior

demo link:https://codesandbox.io/s/apache-echarts-demo-forked-047g0l?file=/index.js

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment] 2023-01-10 07:08
Duplicate of #18143 .

If you don't want to spend some time describing your problem, don't waste others' time by opening the issue again.

**Closed by Ovilia** 2023-01-10 07:08 UTC
Labels: bug, pending, duplicate, en
