### ISSUE TITLE
[Feature] link x and y axisPointers to snap to series 

### ISSUE THREAD

**Issue by djdjoko** [apache/echarts#17831] opened 2022-10-26 05:52 UTC
### What problem does this feature solve?

The current snapping functionality snaps to the x or y value that is the closest to the cursor. What would be even more useful is to snap simultaneously to the closest x and y value of the series since users mostly are not interested in seeing values of x and y values that are independent. Further it would simplify and streamline the user experience of using the chart. 

Please find an example below how that would look if snapping would be linked.

![image](https://user-images.githubusercontent.com/902354/197944773-61be10dc-7242-47b9-a696-6bfa8687ca2c.png)

https://codepen.io/djdjoko/full/xxzKJYJ

    

### What does the proposed API look like?

axisPointer property would need to be added to 'grid' property or axisPointers need or axisPointer snap defined on xAxis needs to be linked to axisPointer snap on yAxis

**Comment by Ovilia** [comment] 2022-10-27 03:55
Duplicate of #16675

**Closed by Ovilia** 2022-10-27 03:55 UTC
Labels: new-feature, duplicate

**Comment by JingXiansen** [comment] 2023-05-06 01:47
Has the function of line chart been realized?

**Comment by francisashley** [comment] 2023-09-03 12:28
This would be really convenient to include, has any progress been made with it?
