### ISSUE TITLE
[Bug] Population bar graph. The stack value 0 is not in the starting position.

### ISSUE THREAD

**Issue by lionants02** [apache/echarts#17942] opened 2022-11-19 18:50 UTC
### Version

5.4.0

### Steps to Reproduce

1. Go to [https://echarts.apache.org/examples/en/editor.html](https://echarts.apache.org/examples/en/editor.html)
2. And paste the information below.
```javascript
option = {
    tooltip: {
        trigger: 'axis',
        axisPointer: {
            type: 'shadow'
        },
        valueFormatter: (value) => Math.abs(value)
    },
    legend: {
        itemWidth: 30,
        itemHeight: 30,
        data: [
            {
                name: 'Male',
                icon: 'path://m 146.41936,238.8034 c -5.21101,-1.43402 -7.51545,-6.79358 -6.6619,-11.76943 -0.0588,-45.10952 -0.11757,-90.21905 -0.17635,-135.328563 -5.3022,-1.61412 -3.06375,4.34199 -3.52464,7.58816 -0.0576,14.697923 -0.11511,29.395843 -0.17266,44.093773 -1.72718,6.61806 -12.15586,7.45944 -14.19605,0.88682 -1.42909,-4.98857 -0.22146,-10.60033 -0.62062,-15.83232 0.10773,-15.18837 -0.21551,-30.437173 0.16059,-45.587893 1.91842,-11.228608 12.80383,-20.22421 24.26927,-18.689786 10.60777,1.558898 0.0755,-3.65768 -0.79236,-8.596161 -4.23852,-8.688715 0.80002,-20.073014 9.72708,-23.421847 8.82591,-4.162774 20.30103,1.001172 23.52581,10.108188 2.28945,5.67583 1.4368,12.853955 -2.76118,17.571486 -5.15831,4.024926 -3.94241,5.010805 1.85043,4.362909 13.58742,-1.603119 25.03585,11.840701 23.9554,24.967141 -0.0691,18.213333 -0.13818,36.426673 -0.20726,54.640013 -1.5351,4.55905 -7.30638,6.71543 -11.30858,3.96578 -4.81473,-2.8888 -2.73019,-9.20279 -3.19227,-13.88869 -0.0523,-14.05586 -0.10469,-28.11173 -0.15704,-42.167583 -4.85271,-1.54237 -3.37467,3.24601 -3.51022,6.4208 V 231.02616 c -1.3114,6.77368 -9.29063,10.3384 -15.13544,6.61747 -6.62075,-3.7866 -4.17124,-12.04397 -4.62011,-18.29166 v -70.84935 c -4.85175,-1.54283 -3.39102,3.24111 -3.53094,6.42079 -0.0578,25.5528 -0.11553,51.1056 -0.17329,76.65839 -1.7387,5.48439 -7.13811,8.77105 -12.74767,7.2216 z',
            },
            {
                name: 'Female',
                icon: 'path://m 39.7122,238.0264 c -5.604205,-1.49359 -5.822698,-7.32898 -5.431108,-11.96235 -0.05932,-18.97406 -0.118632,-37.94813 -0.177948,-56.92219 -7.401109,0.0507 -14.802279,0.16954 -22.203547,0.1438 8.050221,-26.97466 15.83106,-54.03787 24.0791,-80.948455 -6.246873,-1.537447 -5.103818,6.332986 -7.12857,10.198179 -4.203419,12.783656 -7.28462,25.995046 -12.31951,38.467156 C 6.215777,147.43407 -0.93895389,129.58252 6.2279437,121.52707 11.709639,105.71684 15.006783,88.999576 22.521999,73.9779 25.487431,65.143259 38.425956,64.174487 43.879817,63.247984 35.242261,58.307767 32.195248,46.181151 37.843175,37.985287 c 5.35176,-7.73122 16.727442,-10.988636 24.757146,-5.16531 11.321083,6.562216 10.452089,25.024381 -1.135269,30.670395 9.830628,-0.28155 20.086569,3.623662 24.845207,12.765524 3.87086,7.45858 5.12438,16.169298 8.137928,24.037484 2.906124,10.26421 6.922833,20.35157 9.297803,30.70045 1.06345,4.17564 -1.66552,9.02385 -6.181687,9.2796 -7.686885,1.11419 -8.783192,-8.80355 -10.70406,-14.18732 -3.87502,-12.5653 -7.681429,-25.15172 -11.575988,-37.711005 -8.798872,-0.113812 1.949333,13.898795 1.781574,19.941085 6.048408,20.20812 12.13493,40.40517 18.089502,60.64114 -7.392371,0.35953 -14.803078,0.14681 -22.203496,0.20388 -0.06597,21.22546 -0.131933,42.45093 -0.1979,63.67639 -2.103142,7.13406 -13.415648,7.74398 -15.969932,0.84281 -1.418088,-4.77754 -0.245017,-10.18282 -0.655178,-15.20454 l -0.156843,-49.31466 c -4.44248,-1.05339 -5.844521,0.93365 -4.913879,5.25338 -0.162881,19.18788 0.325808,38.44483 -0.244801,57.58947 -0.334387,5.03435 -6.719798,7.8699 -11.101102,6.02234 z',
            }
        ]
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis: [
        {
            type: 'value',
            show: true,
            axisLabel: {
              formatter: function (params) {
                  return Math.abs(params);
              }
            }
        }
    ],
    yAxis: [
        {
            type: 'category',
            axisTick: {
                show: false
            },
            nameTextStyle:{
              fontStyle:'oblique',
              fontWeight:'bold'
            },
            data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
        }
    ],
    series: [
        {
            name: 'Female',
            type: 'bar',
            color: '#ff007f',
            stack: 'Total',
            label: {
                show: true,
                position: 'right'
            },
            emphasis: {
                focus: 'none'
            },
            data: [320, 302, 341, 374, 390, 450, 0]
        },
        {
            name: 'Male',
            type: 'bar',
            color: '#0000ff',
            stack: 'Total',
            label: {
                show: true,
                position: 'left',
                formatter: function (params) {
                    return Math.abs(params.value);
                }
            },
            emphasis: {
                focus: 'none'
            },
            data: [-120, -132, -101, -134, 0, -230, -210]
        }
    ]
};
```

### Current Behavior

![image](https://user-images.githubusercontent.com/5077672/202866432-b89fbcae-78e8-40ef-ace0-e61ccdeca02a.png)
When there is a stack value of 0, the display is aligned to the right.

### Expected Behavior

I want 0 to be centered.

### Environment

```markdown
- OS: Windows 11
- Browser: Chrome
- Framework:
```

### Any additional comments?

I ran into a problem on Grafana so I tested it on the Apache Echarts editor and got the same problem.
Now I use the method, when 0 is found, return '' .

**Comment by lionants02** [comment] 2022-11-19 19:00
i can fix it Just migrate data in series to Male first.

**Comment by lionants02** [comment] 2022-11-19 19:02
After moving the Male data up first, there was a problem, the Female data aligned to the left instead.
![image](https://user-images.githubusercontent.com/5077672/202867234-b0d3bc32-e53f-4745-98a4-5635317d573c.png)

**Comment by plainheart** [comment] 2022-11-20 06:30
Fixed by #17809

**Closed** 2022-11-20 06:30 UTC
Labels: bug, en, resolved, topic: stack

**Comment by plainheart** [comment] 2022-11-21 08:14
Hi @lionants02, we reverted the changes in #17809 as it's not a bug. You can set [`stackStrategy`](https://echarts.apache.org/option.html#series-bar.stackStrategy) to `'negative'` to do it.

**Comment by Ovilia** [comment] 2022-11-21 08:18
@lionants02 Thanks for your contribution and sorry that I misunderstood the problem.
