### ISSUE TITLE
[Bug] 多实例折线图connect联动，遇空值除选中实例外其他实例tooltip不显示，dispatchAction也一样

### ISSUE THREAD

**Issue by destiny941028** [apache/echarts#20352] opened 2024-09-18 03:00 UTC
### Version

5.5.1

### Link to Minimal Reproduction

https://github.com/destiny941028/test/blob/main/1726627218475.html

### Steps to Reproduce

多实例折线图connect联动，遇空值除选中实例外其他实例tooltip不显示，dispatchAction也一样

### Current Behavior

多实例折线图connect联动，遇空值除选中实例外其他实例tooltip不显示，dispatchAction也一样（即便场景中一个实例画多条线，任意条线的值为空，也一样不能展示，无法满足业务诉求。）
![image](https://github.com/user-attachments/assets/18d82617-7d14-4fbf-9e72-3e99578a98d8)

### Expected Behavior

应该所有实例的tooltip都显示，
![image](https://github.com/user-attachments/assets/33a3faeb-9d73-42fd-83b7-f3e994339fb5)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment] 2024-09-18 18:38
duplicate of #20058

**Comment by destiny941028** [comment] 2024-09-19 02:56
@helgasoft Thanks for your help, this example helped me avoid the problem.

**Closed** 2024-09-19 02:58 UTC
Labels: bug, pending
