### ISSUE TITLE
[Bug] visualMap pieces legend running out of view

### ISSUE THREAD

**Issue by MeMeMax** [apache/echarts#17680] opened 2022-09-21 14:30 UTC
### Version

5.3.3

### Link to Minimal Reproduction

https://jsfiddle.net/5swqt09a/1/

### Steps to Reproduce

1. Go to jsfiddle
2. click on "Change Visual Map SplitNumber"

### Current Behavior

visualMap legend runs out of view without breaking to next line.

### Expected Behavior

The legend should respect the place it has and break if there is not enough space.

### Environment

```markdown
- OS:Windows
- Browser: Chrome
- Framework: Angular
```

**Comment by plainheart** [comment] 2022-09-22 07:57
Duplicate of #17659

**Closed by plainheart** 2022-09-22 07:57 UTC
Labels: bug, pending, duplicate, en
