### ISSUE TITLE
[Bug] On radar chart, axisName overflow option doesn't work

### ISSUE THREAD

**Issue by leonarf** [apache/echarts#20146] opened 2024-07-11 13:54 UTC
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQBCAhgM4QDGsASrQCa0BOsAwgAseYSkQC-AGiK4A5jmgcCqYrC5haBANqUAglizAmtMDg6xqAVw5yRE2LqZgLtLLADKIeRwjQZlALriUujcnDxKROgA9FGw9EKeVEwQ3Ey4lMHEPt5GYMDcWpHESLDQtAC2-PZuLjj0sADy0Dh2ACoA7sBtAtw4LbAAYsAW3HYDEABu_W4QpHZuOFPQdgCiEDICYHYAcj79rfIZsOW0pAQAbACsAAzXsJJF6CVllVQ6HOU-EPRgoZAwjWabU63V6_SGIzGk2ms3mi3kq3Wmx2ezahzsJzOsAAjOdbncHionqUKlVKABJaAAM3yJ3-cAOTAE0GABhkAE9AfsQbBWj0-mNhqNBtD5rD3PDlrA1hstrBdkDeejjqcCABmfEEzIqZ6kqh8Cw_YCVXhuCwgED5MBc4FdXn88FCqFTMVzCVLRGylGKg7QI6Y9UADnx921xRJr3sABF4QYQJVoNamty7XywYLISKXe5xQsPdKkXKFftlQHYJcAEwhwlE3WRygAWR4AGscJBfDbeTy0wLBk6szC3XmEQWvfLUUq_RjVbAKzdbvciv4w6dvts9YQicQYjTuHSTAV7EgJi4LDgxABaC8ZR7EJis_JUADEmtuN636GAU24VIM7SoABGvS0M2ogqDWNb0Dg3AQHUhQ6reLxkpY1htrAEz1PQngKD4fhhugYDsok9ihFw3DvkSagaLAmi3k8dHECeWBnloAAsVbXHYGq3HYHE8bAarzpx5aanY2LBrcy4MegSFvPohjGKY5hWDYYEfjWW7KB-6BMSxNFCWJrH4rxEnCRWeL8exxmzti-JSdpMkbg4TguO42HeL4albmIt6BOBRCBGIADcQA

### Steps to Reproduce

I created the chart starting with first radar chart example and just modifying indicators name to be really long and adding option overflow: 'break'.

### Current Behavior

Indicators label should be broken into multiple lines

### Expected Behavior

Indicators label are one only one line and overflows outside of the display zone

### Environment

```markdown
- OS: Linux
- Browser: Firefox and Chrome
- Framework:
```

### Any additional comments?

The following issue seems to be about the same problem : https://github.com/apache/echarts/issues/17209
And it's linked to the followinf Pull Request which seems to fix things but wasn't merged : https://github.com/apache/echarts/pull/17212

**Comment by plainheart** [comment] 2024-07-11 15:18
Thanks for your report. This is a known bug. We will fix it in v6 or some next versions of v5. Duplicate of #20119 and more

**Closed** 2024-07-11 15:18 UTC
Labels: bug, pending, duplicate, en
