### ISSUE TITLE
[Bug] VisualMap 分段颜色重叠

### ISSUE THREAD

**Issue by day-xue** [apache/echarts#19150] opened 2023-09-25 09:34 UTC
### Version

5.2.2

### Link to Minimal Reproduction

no

### Steps to Reproduce

<img width="525" alt="image" src="https://github.com/apache/echarts/assets/95938844/e081b301-4e63-4676-af25-219bba310b7b">

### Current Behavior

使用visualmap的时候 折线图的线条重叠了
<img width="352" alt="image" src="https://github.com/apache/echarts/assets/95938844/fabade8f-0d2c-4ff0-ab18-6cd6168f9bb2">

### Expected Behavior

期待不重叠

### Environment

```markdown
- OS:mac
- Browser:谷歌
- Framework:react
```

**Comment by helgasoft** [comment] 2023-09-26 02:29
duplicate of #18386
@day-xue, please do not repeat issues, it creates clutter. 
Your comment on #18386 is enough feedback to emphasize importance to developers.

**Closed** 2023-09-27 02:53 UTC
Labels: bug, pending, duplicate
