### ISSUE TITLE
[Bug] line-stack图示异常?

### ISSUE THREAD

**Issue by hrj5032188** [apache/echarts#18378] opened 2023-03-14 01:10 UTC
### Version

5.4.1

### Steps to Reproduce

官网例子:
https://echarts.apache.org/examples/zh/editor.html?c=line-stack
Search Engine在只有1300+的数值时
在页面中显示到了2500+的位置上

### Current Behavior

?

### Expected Behavior

!

### Environment

```markdown
- OS:mac 13.2.1 (22D68)
- Browser:Chrome
- Framework:vue
```

### Any additional comments?

asdf

**Comment by helgasoft** [comment] 2023-03-14 03:18
duplicate of #18235

**Closed** 2023-03-14 03:22 UTC
Labels: bug, pending
