### ISSUE TITLE
[Bug] 折线图visualMap里的维度dimension设为非当前系列的值，点的颜色正常，线的颜色没变

### ISSUE THREAD

**Issue by LZF-fe** [apache/echarts#19936] opened 2024-05-15 02:10 UTC
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=line-sections&version=5.5.0

### Steps to Reproduce

**场景：根据维度1的数据生成折线图数据，根据维度2的数据改变点和线的颜色**

 ```
const reasonData = [
  {x: '1', power: 93, state: 1},
  {x: '2', power: 95, state: 3},
  {x: '3', power: 97, state: 1},
  {x: '4', power: 95, state: 3},
  {x: '5', power: 93, state: 1},
]
option = {
  xAxis: {
    type: 'category',
    boundaryGap: false,
  },
  yAxis: {
    type: 'value',
  },
  dataset: {
    dimensions: ['x', 'power', 'state'],
    source: reasonData
  },
  visualMap: [
    {
        show: false,
        dimension: 2,
        // seriesIndex: 0, // 第一部分数据
        pieces: [
            { min: 0, max: 2, color: "red" },
            { min: 2, color: "green" },
        ],
        outOfRange: {  // 不在范围内的
            color: "yellow"
        }
    }
  ],
  series: [
    {
      name: '电量',
      type: 'line',
    }
  ]
};
```

### Current Behavior

折线点的颜色符合预期，但是线的颜色却没变化
![image](https://github.com/apache/echarts/assets/51901783/68a811c1-99e3-4ecc-9694-84bf481b4de7)

### Expected Behavior

折线图的点和线都应该根据state的值变化成相应的颜色

### Environment

```markdown
- OS:Windows10
- Browser:Chrome 124.0.6367.202（正式版本） （64 位）
- Framework:react18.2
```

**Comment by helgasoft** [comment] 2024-05-15 06:38
duplicate of #19270, visualMap _dimension_ can't be >1 for lines, it's an old bug

**Closed** 2024-05-16 07:08 UTC
Labels: bug, pending
