### ISSUE TITLE
Is there any option to generate pdf for chart

### ISSUE THREAD

**Issue by Abhishek-Jetani** [apache/echarts#20142] opened 2024-07-11 07:11 UTC
### What problem does this feature solve?

easy to  generate pdf

### What does the proposed API look like?

getDataURL({ type: 'pdf' });

**Comment by helgasoft** [comment] 2024-07-11 07:27
duplicate of #5181
Try [this solution](https://codepen.io/helgasoft/pen/jOQjzBy). It uses 3rd party library _pdfmake_.
📌 please close issue if problem solved.

**Closed** 2024-07-11 07:29 UTC
Labels: duplicate, en

**Comment by Abhishek-Jetani** [comment] 2024-07-12 13:27
thank you

**Comment by Abhishek-Jetani** [comment] 2024-07-12 13:27
@helgasoft thank you
