### ISSUE TITLE
[Bug] After switching between browser tabs multiple times, the ECharts chart will be lost when returning to the chart page.

### ISSUE THREAD

**Issue by binyx168** [apache/echarts#19963] opened 2024-05-21 10:03 UTC
### Version

e.g.5.2.2

### Link to Minimal Reproduction

After switching between browser tabs multiple times, the ECharts chart will be lost when returning to the chart page.

### Steps to Reproduce

After switching between browser tabs multiple times, the ECharts chart will be lost when returning to the chart page.

### Current Behavior

After switching between browser tabs multiple times, the ECharts chart will be lost when returning to the chart page.

### Expected Behavior

After switching between browser tabs multiple times, the ECharts chart will be lost when returning to the chart page.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment] 2024-05-21 13:40
Duplicate of #19946

**Closed by plainheart** 2024-05-21 13:40 UTC
Labels: bug, pending, duplicate, en
