### ISSUE TITLE
[Question] 如何正确的使用切换主题功能？

### ISSUE THREAD

**Issue by wccd** [apache/echarts#20478] opened 2024-11-06 02:56 UTC
### What problem does this feature solve?

let option = this.chart.getOption();
echarts.dispose(this.chart);
this.chart = echarts.init(dom, "themeName");
this.chart.setOption(option));

当前是这样设置主题的，会导致第二次调用时option已经是前一个主题内容，从而覆盖第二次使用的主题。不确定是否我的使用方式有误。

### What does the proposed API look like?

期望有一个更便捷的切换主题内置方法

**Comment by helgasoft** [comment] 2024-11-06 03:25
Please search issues first, like [that](https://github.com/apache/echarts/issues?q=is%3Aissue+theme+switch).
Duplicate of #18198, #18540

**Comment by wccd** [comment] 2024-11-06 03:32
> Please search issues first, like [that](https://github.com/apache/echarts/issues?q=is%3Aissue+theme+switch). Duplicate of #18198, #18540
I want to know how to switch themes while keeping the option. echart will pollute the options after toggle theme. At this time, the options obtained by using the getOption Api are unreliable.

**Comment by Ovilia** [comment] 2024-11-06 08:48
I would recommend:

```js
const option = {...};
chart.setOption(option);

// reset theme when necessary
chart = echarts.init(dom, 'theme-name');
chart.setOption(option, true); // Use notMerge: true to reset all options before.
```

**Comment by wccd** [comment] 2024-11-06 09:48
> I would recommend:
> 
> ```js
> const option = {...};
> chart.setOption(option);
> 
> // reset theme when necessary
> chart = echarts.init(dom, 'theme-name');
> chart.setOption(option, true); // Use notMerge: true to reset all options before.
> ```

For some reason, I need to record echart's options for the next render. Just like JSON.string(echart.getOption()), But this will carry theme data,So I had to find a way to remove the theme data.

**Comment by Ovilia** [comment] 2024-11-07 05:59
`JSON.string(echart.getOption())` is Okay but the returned value also contains default values from ECharts.

**Closed** 2024-11-11 08:20 UTC
Labels: new-feature, pending
