### ISSUE TITLE
[Bug] visualMap cannot be mapped to dimension different than 0

### ISSUE THREAD

**Issue by frab90** [apache/echarts#19309] opened 2023-11-19 21:22 UTC
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWsBEBnApgJwhywwC5YBtNdZK6zMATxB1MwHM8BDEACwwBpa1DABtODYAFcwrDADNgeAMYtBddBjzBOAW1Zg8knGvUYAJlzZtOAIxEsyBoybrzFK1qnXC8OEJJEsKGhWAFYXUw5OADcIRlYABgA6AEYI1xwzNhwAGRxoNjA-MkpvOgAOBPT1FMqhOgBdetgAX2qMHB1eTiDiMi8y7CVOe31DY2aNOM6AZUZR_snhLB5OM2AAdwAhEUk8VhSEpZbmtubzTjBOVlKygbLMCDNZWtqAZlCBJY1oXQdMV7lD5fB4aaIjIw3b7UWrVbwYACCAGEACoASQAagBREGg9ApUJJAAsAHY4aYAOI46FNB5nB73QZPWQkgBsoQAnKFPuSfn8WeyuTzoRhwbt_rc8YdecIkQiAHJIrE5HJYgAiuKlbySJPC0I0WxmGBpx2aDXaIgg0AA1n0KEtGfCsFJlP8MIDgTKMFc8NkZGQMGzOdzNYMxZCyEc6WaLTg5P7MAkAKShjRgUCyZOpzAbJ5FWShLPtHg4CBsHgJjCFlNCenUR30JhuqK8bOicRSSsKV1trS6MbOc4WThWWwLWBOCbw7seRYPTR-AJBGBhckYKKxeKR1JrzLZPIFfMlaGVGW1KNlWnqOsZLqrXqeJZDEb_Sdr6Y6OYMccN1wrNabDsewHBe3gnGB7RmJc1zHgyIrMgGABMRLlCkbystmri_DobrIah6GYcI4YSvqsCwqRGByoqyqqhqMr4oSCTlPRmAYkaJp0uSv7CAhmBvByRIcikiGEXyOGyPxgnCaJmDEVCeL4lUFFUUqKrqjJDFJExLEYGxxp4leYExuclo2nakrqNxGjOnss6YHhaEYV6Pp-hJAlCSJXpyWQhymt45omXGlbVm26YgJmKbtLmZhHpgIXFqW5bBVmtYRA23pNrILZ8BaHbSLIM6qOcfZ6I44yQZY1h2K-5XnIVj7zr4_iBMEq5PhucQMIkO5PnuuT5IUxT2nip7QueSyGdQN7CJ03QPnOgxYMM45vk-H5fj-Ir_us2y7PsPmgdepyQdB8l3PBzwBuUrIEhyMkYNhbrXbd93ecNCnkQpmAqTR6ksYhyTlIhOkAFoABL6aCk10NNdBWY8l2YM9rIJPdj2yMjqNeRCJFfdKykKqptEaWRRI6RiGocWU4HqAF8KmbaZ3ePD2AunZGDPZy90uTglaY69OOJH5tOxvGEWhRmAbxec0WxVWRbnCWZYVgWKUw2l5yMMwWVcK2uUSPlAb1e0JUDlOpjDqO1Vm-09ULfCTVLq1ZB6vOHVbrAyRpL1WT9YeQ0Wd4o1SnUDzQ607SzfeEB2txz4rbV87rfM_ws9tgF7SBwvq0Op2wedeIYLxHOIddoTlGj_JXaX7IV9j4pM6Cn0KZRhO_XRpEEsSZIUVSkNh8cXEXRj11vAkd1eujV2j-PAsN_nUpKV9rfUWpHd42TFEU_3l7Z9QdOmAz5kOltbNPTX5fc5wvq8yPrJjxPIpvYdMPGfTQWq5FmuS3FCvwrLQ15Zf3hErJKn8d40wPqKGOkgRgAFluCNwAPRIInDwGOsANiKFtEIFBNA6B4OsjwTYrA5AjFwBEQhmAzAQBwtAZcIRIyUNQWmTKAYQCEBULmXAoYqEYGGGAHAbBFCEGPgQlhMIl7UCoficouCJEH3QHw4h0R8A5CtNaUh5DzZKIkUXaAAAlTgBRU7yNMFgBgOgbDABEDMCAAAvXG0iJF0HxuIsotQzGNC8a0Mx008FFAwesIg0AADkYBMHYKEOlFYJCyqDnhDQuhDDWDA01mwzASgYCQGgJIKQxB2g6CtAcRCWlN7wh0JwAAHqkwGaT4TLSUAEMcNUEmmCtEYkxDVBhZJEIoRu8IADEbxHJcnuoMokoRdQ2CJOMkkRI1hmBSOM2wZgOQ4EfoXQZOAEhyDeHIOuIpBlyBOXIGwchxlyBwDsjkWMjlyCgjgG6lyiSsjMESN44yzAkjHohEkKzCwJEQhhCapxaxUCaC0IAA&_source=echarts-doc-preview

### Steps to Reproduce

minimal reproduction is provided

### Current Behavior
the visualMap in the minimal example works if mapped to `dimension: 0` but it doesn't if mapped to `dimension: 2`.
i am experiencing the same behavior with the other visualMap included in the example (commented). it works if mapped to `dimension: 0` but it doesn't if mapped to `dimension: 2`.

### Expected Behavior

both the visualMaps work and they can be mapped to different dimensions.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment] 2023-11-21 02:43
duplicate of #11667  (also #19270,...)
bug is known - dimension >1 does not work

**Closed** 2023-11-21 23:40 UTC
Labels: bug, pending, en

**Comment by frab90** [comment] 2023-11-21 23:46
just for reference, in https://github.com/apache/echarts/issues/19270  [jpfeuffer](https://github.com/jpfeuffer)  stated the bug manifests with dimension>1, in my case the bug manifests also with dimension = 1. it works only on dimension 0.

i closed this and will reply on https://github.com/apache/echarts/issues/19270
