### ISSUE TITLE
[Feature] Data Item information in the onclick params for radar chart

### ISSUE THREAD

**Issue by dirslashls** [apache/echarts#16160] opened 2021-12-02 08:43 UTC
### What problem does this feature solve?

The onclick even handler params do not contain the information about the data point that is clicked. It gives the entire series data. This is probably because of the format in which the radar chart expects the data, name and value which is an array. What is needed is the specific index in this array that is clicked. With the array index it will be possible for me to map it back to the specific record and support say a drill-down based on that record's data.

### What does the proposed API look like?

May be params.dataItemIndex ?

**Comment by Ovilia** [comment] 2021-12-03 10:03
Duplicate of #10537.

**Closed by Ovilia** 2021-12-03 10:03 UTC
Labels: new-feature, pending, en, waiting-for: community
