### ISSUE TITLE
StackedBar chart min height on smaller bar not getting set

### ISSUE THREAD

**Issue by aj186018** [apache/echarts#18154] opened 2023-01-09 11:39 UTC
### Version

4.9.0

### Steps to Reproduce

option = {
  tooltip: {
    trigger: 'axis',
    axisPointer: {
      // Use axis to trigger tooltip
      type: 'shadow' // 'shadow' as default; can also be 'line' or 'shadow'
    }
  },
  legend: {},
  grid: {
    left: '3%',
    right: '4%',
    bottom: '3%',
    containLabel: true
  },
  xAxis: {
    type: 'value'
  },
  yAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  series: [
    {
      name: 'Direct',
      type: 'bar',
      stack: 'total',
      label: {
        show: true
      },
      emphasis: {
        focus: 'series'
      },
      data: [3, 3, 3, 3, 390, 330, 320]
    },
    {
      name: 'Mail Ad',
      type: 'bar',
      stack: 'total',
      label: {
        show: true
      },
      emphasis: {
        focus: 'series'
      },
      data: [120, 132, 101, 134, 90, 230, 210]
    },
    {
      name: 'Affiliate Ad',
      type: 'bar',
      stack: 'total',
      label: {
        show: true
      },
      emphasis: {
        focus: 'series'
      },
      data: [220, 182, 191, 234, 290, 330, 310]
    },
    {
      name: 'Video Ad',
      type: 'bar',
      stack: 'total',
      label: {
        show: true
      },
      emphasis: {
        focus: 'series'
      },
      data: [150, 212, 201, 154, 190, 330, 410]
    },
    {
      name: 'Search Engine',
      type: 'bar',
      stack: 'total',
      label: {
        show: true
      },
      emphasis: {
        focus: 'series'
      },
      data: [820, 832, 901, 934, 1290, 1330, 1320]
    }
  ]
};

### Current Behavior

Using stacked bar chart. if some bar have very high value (100x) where x is minimum value for bar in that stacked bar, it is not/hardly visible on chart

### Expected Behavior

Wanted to be able to force minimum height if even the largest bar in stack is 100x value

### Environment

```markdown
- OS:windows 10
- Browser:chrome
- Framework: angular
```

**Comment by Ovilia** [comment] 2023-01-10 07:11
Duplicate of #17005 . Please follow that issue. A pull request is welcomed.

**Closed by Ovilia** 2023-01-10 07:11 UTC
Labels: bug, pending, duplicate, en
