### ISSUE TITLE
no events are trigger when hover on the area chart and stacked area chart

### ISSUE THREAD

**Issue by karthik-noveau** [apache/echarts#19810] opened 2024-04-10 05:06 UTC
### Version

5.5.0

### Link to Minimal Reproduction

https://github.com/karthik-noveau/e-charts

### Steps to Reproduce

1. clone this repository in local
2. npm install
3. npm start
4. hover on area chart
5. no events are triggered

### Current Behavior

when hover on the area chart , no events are triggered.

I already raised the ticket for area chart hover issue, so you given  one solution .
but, after add the triggerEvents in area and stacked area chart, no events are triggered as your suggestion used
I added in my code , you can check

Here the problem is , you are giving the events for circle of top of each area chart part only , not for area chart part 

this is the previous raised ticket: https://github.com/apache/echarts/issues/19736

### Expected Behavior

![image](https://github.com/apache/echarts/assets/82690268/90125960-0f81-460d-aad5-d3a4c0f18ed8)

### Environment

```markdown
- OS: macOs 
- Browser: chrome
- Framework: React Js
```

**Comment by plainheart** [comment] 2024-04-10 05:36
Duplicate of #19811

**Closed by plainheart** 2024-04-10 05:36 UTC
Labels: bug, pending, duplicate, en
