### ISSUE TITLE
[Bug] Heatmap does not show chart after a large no-data gap

### ISSUE THREAD

**Issue by gzhong88** [apache/echarts#18175] opened 2023-01-15 03:11 UTC
### Version

5.4.1

### Steps to Reproduce

1. Use the following link to create the heatmap: 
https://echarts.apache.org/examples/en/editor.html?c=heatmap-large

2. Replacing line 11 in function generateData(theta, min, max) with 	

        if (i> 10 && i<160) {
		data.push([i, j, undefined]);
	}
	else {
		data.push([i, j, noise.perlin2(i / 40, j / 20) + 0.5]);
	}

### Current Behavior

No chart is shown for x (i.e. i) > 160 and x <= 200.

### Expected Behavior

Chart shall be shown between x (i.e. i) > 160 and x <= 200.

### Environment

```markdown
- OS:Windows 10
- Browser:Chrome Version 109.0.5414.74 (Official Build) (64-bit)
- Framework:
```

**Comment by Ovilia** [comment] 2023-01-16 07:13
Cannot reproduce.

<img width="216" alt="image" src="https://user-images.githubusercontent.com/779050/212618804-49180b66-6540-4ae0-9040-f9bf24baeb0a.png">

Looks as expected to me.

**Comment by gzhong88** [comment] 2023-01-16 20:17
-    
If you cannot reproduce, try to set the no data gap bigger by changing i <160 to i<190 as following, and try again.  Thanks.

   -    
Use the following link to create the heatmap:   
https://echarts.apache.org/examples/en/editor.html?c=heatmap-large

   -    
Replacing line 11 in function generateData(theta, min, max) with
    if (i> 10 && i<190) {
 data.push([i, j, undefined]);
   
}   
else {   
data.push([i, j, noise.perlin2(i / 40, j / 20) + 0.5]);   
}

    On Monday, January 16, 2023 at 01:13:58 AM CST, Wenli Zhang ***@***.***> wrote:  
 
 


Cannot reproduce.



Looks as expected to me.

**Comment by gzhong88** [comment] 2023-01-16 20:19
If you cannot reproduce, try to set the no data gap bigger by changing i <160 to i<190 as following, and try again.  Thanks.
Replacing line 11 in function generateData(theta, min, max) with

if (i> 10 && i<190) {
     data.push([i, j, undefined]);
}
else {
     data.push([i, j, noise.perlin2(i / 40, j / 20) + 0.5]);
}

**Comment by gzhong88** [comment] 2023-01-16 21:25
1. Use the following link to create the heatmap:https://echarts.apache.org/examples/en/editor.html?c=heatmap-large
2. Replacing line 11 in function generateData(theta, min, max) with  if (i> 10 && i<190) {    data.push([i, j, undefined]);  }  else {    data.push([i, j, noise.perlin2(i / 40, j / 20) + 0.5]);  }
3. Click on Run button above the code page on the left to regenerate the chart. Let your mouse cursor focued on the Run button. Do not move your mouse, which is Very Important!!
Observed that chart between i >=190 and i <= 200 do not show up.
Note: If you change above step2 from i<190 to i<120, and click Run button, the remaining chart will show up automatically.

    On Monday, January 16, 2023 at 02:16:53 PM CST, Gong Zhong ***@***.***> wrote:  
 
     
   -    
If you cannot reproduce, try to set the no data gap bigger by changing i <160 to i<190 as following, and try again.  Thanks.

   -    
Use the following link to create the heatmap:   
https://echarts.apache.org/examples/en/editor.html?c=heatmap-large

   -    
Replacing line 11 in function generateData(theta, min, max) with
    if (i> 10 && i<190) {
 data.push([i, j, undefined]);
   
}   
else {   
data.push([i, j, noise.perlin2(i / 40, j / 20) + 0.5]);   
}

    On Monday, January 16, 2023 at 01:13:58 AM CST, Wenli Zhang ***@***.***> wrote:  
 
 


Cannot reproduce.



Looks as expected to me.

**Comment by gzhong88** [comment] 2023-01-17 02:43
To reproduce the problem, after you replaced the line 11 code in above step2 with the following code, then click on Run button. Let your mouse cursor stay focused on the Run button. Do not move your mouse.
(點擊Run按鈕之後，不要移動鼠標，這是Reproduce the problem的關鍵。）
  if (i> 10 && i<190) {
    data.push([i, j, undefined]);
  }
  else {
    data.push([i, j, noise.perlin2(i / 40, j / 20) + 0.5]);
  }
Note: If you change above step2 from i<190 to i<120, and click Run button, you will see a different behavior that the remaining chart will show up automatically.

**Comment by gzhong88** [comment] 2023-01-17 02:45
To reproduce the problem, after you replaced the line 11 code in above step2 with the following code, then click on Run button. Let your mouse cursor stay focused on the Run button. Do not move your mouse.
(點擊Run按鈕之後，不要移動鼠標，這是Reproduce the problem的關鍵。）
if (i> 10 && i<190) {
data.push([i, j, undefined]);
}
else {
data.push([i, j, noise.perlin2(i / 40, j / 20) + 0.5]);
}
Note: If you change above step2 from i<190 to i<120, and click Run button, you will see a different behavior that the remaining chart will show up automatically.
    On Monday, January 16, 2023 at 03:25:05 PM CST, Gong Zhong ***@***.***> wrote:  
 
  1. Use the following link to create the heatmap:https://echarts.apache.org/examples/en/editor.html?c=heatmap-large
2. Replacing line 11 in function generateData(theta, min, max) with  if (i> 10 && i<190) {    data.push([i, j, undefined]);  }  else {    data.push([i, j, noise.perlin2(i / 40, j / 20) + 0.5]);  }
3. Click on Run button above the code page on the left to regenerate the chart. Let your mouse cursor focued on the Run button. Do not move your mouse, which is Very Important!!
Observed that chart between i >=190 and i <= 200 do not show up.
Note: If you change above step2 from i<190 to i<120, and click Run button, the remaining chart will show up automatically.

    On Monday, January 16, 2023 at 02:16:53 PM CST, Gong Zhong ***@***.***> wrote:  
 
     
   -    
If you cannot reproduce, try to set the no data gap bigger by changing i <160 to i<190 as following, and try again.  Thanks.

   -    
Use the following link to create the heatmap:   
https://echarts.apache.org/examples/en/editor.html?c=heatmap-large

   -    
Replacing line 11 in function generateData(theta, min, max) with
    if (i> 10 && i<190) {
 data.push([i, j, undefined]);
   
}   
else {   
data.push([i, j, noise.perlin2(i / 40, j / 20) + 0.5]);   
}

    On Monday, January 16, 2023 at 01:13:58 AM CST, Wenli Zhang ***@***.***> wrote:  
 
 


Cannot reproduce.



Looks as expected to me.

**Comment by gzhong88** [comment] 2023-01-17 02:53
![image](https://user-images.githubusercontent.com/122709233/212799461-3b54ab7b-dde1-49d1-87f7-63eb53fa5656.png)

**Comment by Ovilia** [comment] 2023-01-18 02:29
Cannot reproduce even with mouse hoving Run button.

**Comment by gzhong88** [comment] 2023-01-18 16:04
Above Heatmpa_issue.pptx contains a recorded video which shows how the issue can be reproduced.
Just click at Heatmpa_issue.pptx link to download and open it, then click at the play button at the bottom to see the video.
![image](https://user-images.githubusercontent.com/122709233/213226469-ecb383b6-deae-4de1-82f7-f9272a160d58.png)

Explanation of the video: 
In the beginning part of the video, after I copied & pasted the code and clicked the Run button. I intentionally moved my mouse to trigger the drawing of the remaining chart.
In the late part of the video, after I copied & pasted the code and clicked the Run button. I hand off my mouse to prevent trigger mouse event(點擊Run按鈕后，手馬上離開鼠標，以防移動鼠標trigger Event). You can see the rest part of chart was not drawn.

**Comment by gzhong88** [comment] 2023-02-02 17:57
Please view the video in the Heatmap_issue.pptx file, which I uploaded above, to observe how the issue can be reproduced.
Give some feedbacks please.

**Comment by plainheart** [comment] 2023-02-14 02:07
Duplicate of #18266

**Closed** 2023-02-14 02:07 UTC
Labels: bug, en
