### ISSUE TITLE
[Bug] Phantom mark points

### ISSUE THREAD

**Issue by tandem97** [apache/echarts#20057] opened 2024-06-20 16:43 UTC
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoW6MCIAmBDMuAWsMALaYBcsA2kpmAJ4gCmlsmE0AzhNqwL4AaZPSasqmLgBtezAE6Z-AXUFoM6zFOYBzZtGxskQtevST5EZlza0TpjdFylx7MFbCZV9-6JZtNnKxe3hp4BDZ0AG64UgCuLgAsQiLRcS4ArMlRMfFsAAxZmKm5VADshcUZFTkuAJzVaWz1wtmNVAAcDSWwnS1FNWwAzMrBIWakuHIA1gAKwJweVKhj3jj4uBGYAMYkcgZU1HnCCSrslf55ALQJii12Kz47wHs2AIzC6Sr3DxrnEq-XdKYb4rQpPF4HABMwjyp36bXYkMueVuInB-xog2EpThf3Yg0upVRyx-q3RNgSHy-pNWeMwCUBwJp6DBuwx1HSwlquIGEnSl1qxO2bJsADYuTyEZhRQLiSDScLnuzSsJ2tTmb9eexSpd2kzmaylTZ2qrJd1MO1dULyQdasJBmaXJhapdBoolPL1Px5SN5ZgAB4AQX9EGsBzoYQ2ByOsHesGhsCxsEpsE5sHFsBVPQlvpCmAYwdDmy4WxiLjAcniyhQ_AA3EA

### Steps to Reproduce

1. Zoom to see a few points
2. Disable the line
3. Pan left or right along the chart with the line disabled
4. Enable the line again
5. You will see phantom mark points that were on your screen on step 2

### Current Behavior

Phantom mark points on canvas

### Expected Behavior

Only valid points on canvas

### Environment

```markdown
- OS: Ubuntu/Windows
- Browser: Chrome/Firefox
- Framework: -
```

**Comment by helgasoft** [comment] 2024-06-25 02:26
duplicate of #19125

**Closed** 2024-07-02 07:36 UTC
Labels: bug, pending, en
