### ISSUE TITLE
Bar Chart: Hide Bar which are having values 0 in them

### ISSUE THREAD

**Issue by SonaliPI** [apache/echarts#19250] opened 2023-10-27 06:36 UTC
### Version

5.4

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=dataset-simple0

### Steps to Reproduce

In Multiple Bar chart , if some data value has zero then it is not hiding fully in chart, it is taking space in between them.
![image](https://github.com/apache/echarts/assets/149141850/f7e56b2c-48b5-43a2-916a-72ac8dad363b)
[](url)
![chartIssue](https://github.com/apache/echarts/assets/149141850/c1424004-b379-4b6c-a79a-0e1da452a47c)

### Current Behavior

In Multiple Bar chart , if some data value has zero then it is not hiding fully in chart, it is taking space in between them.

### Expected Behavior

Hide Bars in chart if the value is 0 or null or undefined.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by MatthiasMert** [comment] 2023-10-27 06:46
You could try using `xAxis: {type: 'value}` as outlined [here](https://stackoverflow.com/questions/77160878/echarts4r-bar-plot-how-to-prevent-x-axis-categories-from-being-plotted-if-th/77187313#77187313) and see if it resolves your use case.

**Comment by helgasoft** [comment] 2023-10-27 19:30
duplicate of #9899
@MatthiasMert, thank you for the link - good brainstorming and a viable solution from [Kikon](https://stackoverflow.com/users/16466946/kikon).
Hope it will put to rest that recurring issue.
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PTAEEMBNwBwFwKaVAMwE4HsC2oAWc4YBnALhAGMNIEYEA7AOgEsNgBrJtjOgWkldp1gAeQBSaAKIBpAEJSAUJTpE4oAOYAbDACNwGgMIYtaIqAC8qAK51ycFnVAAKOgElEWIgEpQAb3mhQJRVQBHIXZThwGwRzEPJccDQ4ImY6JjhHfnJLLHo4BnI0BHBECQ0EXLoMgHJyKIA3cCJqz08Abn848JUo8gQGIgQ4YXh7Rx8AX3bOoNVKYyIABljQ7sjohjUhkbtuR08Coww0ABpOgPnj0wtLk0WOgIB3XCZyp1uU8ro1OFxQAB5QK53F5fOdAkcTAwYJYiLhHAxER9FtMAhNOqsIr1-pAmEQYBhBvsHqAinBLGgHB8BhomH1HIsTkC3BUvB0Jh15ChrLZ7BCsNomHQEAA5bgALQQmAAanpLAgiAAxTBYADKUqYCscnT0GnVaE1RDOAQAHgBBE14gAy4G0CA0RpmkOu6i0ugMzscuv1hoYXx-uE88m8fgCIFAAFUAAoAESBGEQoG0AE9QAAJe1qJoYFBwEikioYeoxNQGyDhagm0AAMlA5stRArCCrcAwoFhMXSoB6dGgWmFnXDZIpylAvxiGFG3FAOgAVqFVChjmPcDF4olVI90rgMJZVAAvKWEwdgb0ahXdneWDTIO0QByJNDgVM5oE5DXkCBoJ_Jo0hcDxDOKArgqMSPs-ph4ieECgNAkSDKoXrqJglgwEBSaJKYr7jt24C5BCxieEyUTIHCu43ng4DFjBdA5HaaBAdBjQaPKpgIAAjpYehjm2OF0G2r71tatr2ik0EACqrm-ApSuhHyXuRt4xBxXEaDxIHSfR6FwU0QymF6Gh6uenz0AGQYXNwwR0DGJS6cksRngaCp-qZvzGgEQI2ZELIeLEQlEDadoOi53y_G0oDhsujmGgA2osAC6IUBk6ETdsZhgCkKSCxDF8XuQEzGsYqxyBaJOV5eCWB4kQQpqOJdJsC6uX5XgTCQNQdD6CUCBqMchrlUy4Z1IgvVOaYvwlJR1H8bBtngi87X0F5dkutFzkoBoJQALKwI4mS2QhTJCpW3hmAAfOCAQ6QhDAoK8iBoHt9SnWdoDPUlvzmGYFjLAA_KAx3NqA-a5eCqIRWA116Suk0JNNbb8bwh6YLNkRfjERRYEW2XoNgb14qpO0wPInTlKoVY_QwACsLXZN-eSlRososTEP20xSRRVPV5BsMz8qxIy4KtpEGgyJhAskkuDGOGTqPgD5LiQBToD3HLCtKwCnm2T5RDhTp6smgA1IbIbgrLwKssVaBdSNxypj9JIBGtKRSxIAHwtyNi7A4jiDGNy1MqWu4wIrJqmx5HmzG93EWH7hrLTF-vuKH8WOx5TDAY4zHhxHHlxwqGWCsKkDQrC8I-NHLP5sxTImoHKEwPmQeoaHoBTGnEdG4bHceRbHhWzbPV28bPcBMLehiyYI-XW34Lt-CdOc3AjN8zEhsWH3SrHIPo2pmAABMaeFQqVuMykMJwo4i8MyJTNygg4MXBzN9BavoDr8yIID91u8RaAh8L0sqoOgW1qq1W5o1WIm9v62zQKmHgoAACMacqpEBqt8CB58y7alzqAREDAzTfmfLdFUODcG-FAP6X4-YQFgIwQ1UwEwWoR0cAAfSZGwF6gRn5cwam_Q2oA2DvyQTPcyHlH7cPprwnm_CN46xgUPOBacM5OGgdvH-dsvo_RzhHBaHUd59WchfeEScKihwkeiNEJMAjDkpGCCOUM8ygBihXIgu40B9HzPnIghcsrIAmBVCO9QCZ6CJiDGeoZyFwGTLQfM1QYCaj6FuQY1RmGRw0WNfMhCfwkOwOMShrlcA0OWghRhTI2FHRejPXRbUOolL0qkcgLFqBEEcEwbw_1aKGWBgDapoADh3Q0A9PaYdzCvSrAAQm-m-QyRE-lCgAEpRC2PmSJ5CCLHHzNSQZwyKkAy4RMvRS0DoNKFE0ywLS2mtD6UwvprZG6gGqFTKmABSVJfSDRqHwPmRBiwZ6WI8oEjy_lwm4LWbncMd0TCqHAA2VAy5NpBT_DNOwPNQBYESI1PppY2pNhND8tJY8YkIDicfd56yMX4rrKABBixqaEoBlUKUzF8x0ppn02FeIIGrL6QEKhRSVY3IZfiWky8so8vWQEMijx8woD0IMIVHKGyMwlZKqWGKCBSizvfHRkqo5tWVsfLeaAz6pErMIFA2qWYSPWSotpGszo_RrLWI5nUMm-kBiaC19rRmAhRPYyVEdbEOH8mfGKBrU68o8gCwNwbHnVFHtGhlAQlxVAAOoICYF8px1RtBGEgNUG5_y0ngojuGcAaUlDQDgRAOFUsxwMJnHQDQyZsVljxQSvpOkslEOTI4ceotMIDNeBoRw1QWgMuibEx5w1FHJnJeQgkNVvZxLzQQbAC7cGcqINygNtqmVoGYm03szZdW2szqg9BdUGFmubN6z13hHUqzPZKuNcqHQIETRHGNr6hgjjHGgeUX627JoKaFAVAAOJktJhSqmieUVZoAtyQGoaAAAzLPdZP6rERyBQEZMFo8Qg1LchXFJ6qWIKZHQPCJLHm-OLk4ZGhIQgmnOdQSAnhN0eRANuq04qKHStlfKmIP6AktW8aC3OJGiXTtzYkLjEd6CUGoKq9ZVLqgmgU7nZMpL76Fqwwy_yHbKOgAIw2Yz_zwTxU6ByeQ6IuQ8m9oyv2wxPmOEnHAJk3jsnPlroRgKt9QTgo8wwfyDBrBwgzhkPp0mPJTto7UDJ87QPdrrP5s-RbcESJC2ZvE4XlAvFzOMajuQ4nCE-UKPQ1R54BHBN53tDAijFhMAgfYDAMUwD2t45aXCSMhe8flyLRXYvxdXfJhlqXuu2T8-Z8jJBGSmf8x2v5uD26gDnmIgIIWcXIAsDFCJBTcz5gAGwLc-d80AVMFurizRd6oaHXmpIhFUcAQoVVwEAwgW5YK-nlCO6AU7TJztOKu0ye5cTnlvKZDd7NcSHtQ-e5EN7t8SAff5j-yNEcQvBKIITWAcVEreLxbEerOT-VpzjR5kk9mo6ztGv1Pb1QzRPeqDIFn-gWcxmqJGqbaM9vON-UyQXKsmQJSZDFEXoAADsTIoMqzys447TIACcTIZcA_iqASN8hGgMQ8_Yej2UbjYCLqKCUR5V5KhVD6LUvPwBMjp4Ytk8h9fcEN5ACwQoXPlaze5qcnUTd-K88ZAOgR3UKmmPILAyZ9AJCSAMbY_u_fe3d-0IAA)
![image](https://github.com/apache/echarts/assets/13038071/c7d88a9a-8571-4972-8e2e-a028537fb5c8)

**Comment by Ovilia** [comment] 2023-10-30 06:11
We do not have plan to support this for now. You may use custom series if you want.

**Comment by Ovilia** [comment] 2023-10-30 06:12
Close for duplication

**Closed by Ovilia** 2023-10-30 06:12 UTC
Labels: duplicate, en

**Comment by SonaliPI** [comment] 2023-10-31 06:35
@Ovilia Can you please tag which is duplicate one?

**Comment by shiraineko** [comment] 2024-09-20 01:44
> duplicate of #9899 @MatthiasMert, thank you for the link - good brainstorming and a viable solution from [Kikon](https://stackoverflow.com/users/16466946/kikon). Hope it will put to rest that recurring issue. [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PTAEEMBNwBwFwKaVAMwE4HsC2oAWc4YBnALhAGMNIEYEA7AOgEsNgBrJtjOgWkldp1gAeQBSaAKIBpAEJSAUJTpE4oAOYAbDACNwGgMIYtaIqAC8qAK51ycFnVAAKOgElEWIgEpQAb3mhQJRVQBHIXZThwGwRzEPJccDQ4ImY6JjhHfnJLLHo4BnI0BHBECQ0EXLoMgHJyKIA3cCJqz08Abn848JUo8gQGIgQ4YXh7Rx8AX3bOoNVKYyIABljQ7sjohjUhkbtuR08Coww0ABpOgPnj0wtLk0WOgIB3XCZyp1uU8ro1OFxQAB5QK53F5fOdAkcTAwYJYiLhHAxER9FtMAhNOqsIr1-pAmEQYBhBvsHqAinBLGgHB8BhomH1HIsTkC3BUvB0Jh15ChrLZ7BCsNomHQEAA5bgALQQmAAanpLAgiAAxTBYADKUqYCscnT0GnVaE1RDOAQAHgBBE14gAy4G0CA0RpmkOu6i0ugMzscuv1hoYXx-uE88m8fgCIFAAFUAAoAESBGEQoG0AE9QAAJe1qJoYFBwEikioYeoxNQGyDhagm0AAMlA5stRArCCrcAwoFhMXSoB6dGgWmFnXDZIpylAvxiGFG3FAOgAVqFVChjmPcDF4olVI90rgMJZVAAvKWEwdgb0ahXdneWDTIO0QByJNDgVM5oE5DXkCBoJ_Jo0hcDxDOKArgqMSPs-ph4ieECgNAkSDKoXrqJglgwEBSaJKYr7jt24C5BCxieEyUTIHCu43ng4DFjBdA5HaaBAdBjQaPKpgIAAjpYehjm2OF0G2r71tatr2ik0EACqrm-ApSuhHyXuRt4xBxXEaDxIHSfR6FwU0QymF6Gh6uenz0AGQYXNwwR0DGJS6cksRngaCp-qZvzGgEQI2ZELIeLEQlEDadoOi53y_G0oDhsujmGgA2osAC6IUBk6ETdsZhgCkKSCxDF8XuQEzGsYqxyBaJOV5eCWB4kQQpqOJdJsC6uX5XgTCQNQdD6CUCBqMchrlUy4Z1IgvVOaYvwlJR1H8bBtngi87X0F5dkutFzkoBoJQALKwI4mS2QhTJCpW3hmAAfOCAQ6QhDAoK8iBoHt9SnWdoDPUlvzmGYFjLAA_KAx3NqA-a5eCqIRWA116Suk0JNNbb8bwh6YLNkRfjERRYEW2XoNgb14qpO0wPInTlKoVY_QwACsLXZN-eSlRososTEP20xSRRVPV5BsMz8qxIy4KtpEGgyJhAskkuDGOGTqPgD5LiQBToD3HLCtKwCnm2T5RDhTp6smgA1IbIbgrLwKssVaBdSNxypj9JIBGtKRSxIAHwtyNi7A4jiDGNy1MqWu4wIrJqmx5HmzG93EWH7hrLTF-vuKH8WOx5TDAY4zHhxHHlxwqGWCsKkDQrC8I-NHLP5sxTImoHKEwPmQeoaHoBTGnEdG4bHceRbHhWzbPV28bPcBMLehiyYI-XW34Lt-CdOc3AjN8zEhsWH3SrHIPo2pmAABMaeFQqVuMykMJwo4i8MyJTNygg4MXBzN9BavoDr8yIID91u8RaAh8L0sqoOgW1qq1W5o1WIm9v62zQKmHgoAACMacqpEBqt8CB58y7alzqAREDAzTfmfLdFUODcG-FAP6X4-YQFgIwQ1UwEwWoR0cAAfSZGwF6gRn5cwam_Q2oA2DvyQTPcyHlH7cPprwnm_CN46xgUPOBacM5OGgdvH-dsvo_RzhHBaHUd59WchfeEScKihwkeiNEJMAjDkpGCCOUM8ygBihXIgu40B9HzPnIghcsrIAmBVCO9QCZ6CJiDGeoZyFwGTLQfM1QYCaj6FuQY1RmGRw0WNfMhCfwkOwOMShrlcA0OWghRhTI2FHRejPXRbUOolL0qkcgLFqBEEcEwbw_1aKGWBgDapoADh3Q0A9PaYdzCvSrAAQm-m-QyRE-lCgAEpRC2PmSJ5CCLHHzNSQZwyKkAy4RMvRS0DoNKFE0ywLS2mtD6UwvprZG6gGqFTKmABSVJfSDRqHwPmRBiwZ6WI8oEjy_lwm4LWbncMd0TCqHAA2VAy5NpBT_DNOwPNQBYESI1PppY2pNhND8tJY8YkIDicfd56yMX4rrKABBixqaEoBlUKUzF8x0ppn02FeIIGrL6QEKhRSVY3IZfiWky8so8vWQEMijx8woD0IMIVHKGyMwlZKqWGKCBSizvfHRkqo5tWVsfLeaAz6pErMIFA2qWYSPWSotpGszo_RrLWI5nUMm-kBiaC19rRmAhRPYyVEdbEOH8mfGKBrU68o8gCwNwbHnVFHtGhlAQlxVAAOoICYF8px1RtBGEgNUG5_y0ngojuGcAaUlDQDgRAOFUsxwMJnHQDQyZsVljxQSvpOkslEOTI4ceotMIDNeBoRw1QWgMuibEx5w1FHJnJeQgkNVvZxLzQQbAC7cGcqINygNtqmVoGYm03szZdW2szqg9BdUGFmubN6z13hHUqzPZKuNcqHQIETRHGNr6hgjjHGgeUX627JoKaFAVAAOJktJhSqmieUVZoAtyQGoaAAAzLPdZP6rERyBQEZMFo8Qg1LchXFJ6qWIKZHQPCJLHm-OLk4ZGhIQgmnOdQSAnhN0eRANuq04qKHStlfKmIP6AktW8aC3OJGiXTtzYkLjEd6CUGoKq9ZVLqgmgU7nZMpL76Fqwwy_yHbKOgAIw2Yz_zwTxU6ByeQ6IuQ8m9oyv2wxPmOEnHAJk3jsnPlroRgKt9QTgo8wwfyDBrBwgzhkPp0mPJTto7UDJ87QPdrrP5s-RbcESJC2ZvE4XlAvFzOMajuQ4nCE-UKPQ1R54BHBN53tDAijFhMAgfYDAMUwD2t45aXCSMhe8flyLRXYvxdXfJhlqXuu2T8-Z8jJBGSmf8x2v5uD26gDnmIgIIWcXIAsDFCJBTcz5gAGwLc-d80AVMFurizRd6oaHXmpIhFUcAQoVVwEAwgW5YK-nlCO6AU7TJztOKu0ye5cTnlvKZDd7NcSHtQ-e5EN7t8SAff5j-yNEcQvBKIITWAcVEreLxbEerOT-VpzjR5kk9mo6ztGv1Pb1QzRPeqDIFn-gWcxmqJGqbaM9vON-UyQXKsmQJSZDFEXoAADsTIoMqzys447TIACcTIZcA_iqASN8hGgMQ8_Yej2UbjYCLqKCUR5V5KhVD6LUvPwBMjp4Ytk8h9fcEN5ACwQoXPlaze5qcnUTd-K88ZAOgR3UKmmPILAyZ9AJCSAMbY_u_fe3d-0IAA) ![image](https://private-user-images.githubusercontent.com/13038071/278740865-c7d88a9a-8571-4972-8e2e-a028537fb5c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTY5MjgsIm5iZiI6MTcyNjc5NjYyOCwicGF0aCI6Ii8xMzAzODA3MS8yNzg3NDA4NjUtYzdkODhhOWEtODU3MS00OTcyLThlMmUtYTAyODUzN2ZiNWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDAxNDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhOTk0OTdhYzY5MDNjZGJmODM4OWI0ZmQ4YTdkYjMyMTQ0OWZhMDZlYjA5OTJjOGNkYTBjMDkyNWZiMjZhMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n-oGfcfsO3SpQb75xjbSarj-hgF21nojfTSujM561Nw)

Hi @helgasoft , may I know how to remove the Original chart and show only the Combined (zero excluded) chart?

**Comment by shiraineko** [comment] 2024-09-21 02:53
> @shiraineko - [Demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PTAEEMBNwBwFwKaVAMwE4HsC2oAWc4YBnALhAGMNIEYEA7AOgEsNgBrJtjOgWkldp1gAeQBSaAKIBpAEJSAUJTpE4oAOYAbDACNwGgMIYtaIqAC8qAK51ycFnVAAKOgElEWIgEpQAb3mhQJRVQBHIXZThwGwRzEPJccDQ4ImY6JjhHfnJLLHo4BnI0BHBECQ0EXLoMgHJyKIA3cCJqz08Abn848JUo8gQGIgQ4YXh7Rx8AX3bOoNVKYyIABljQ7sjohjUhkbtuR08Coww0ABpOgPnj0wtLk0WOgIB3XCZyp1uU8ro1OFxQAB5QK53F5fOdAkcTAwYJYiLhHAxER9FtMAhNOqsIr1-pAmEQYBhBvsHqAinBLGgHB8BhomH1HIsTkC3BUvB0Jh15ChrLZ7BCsNomHQEAA5bgALQQmAAanpLAgiAAxTBYADKUqYCscnT0GnVaE1RDOAQAHgBBE14gAy4G0CA0RpmkOu6i0ugMzscuv1hoYXx-uE88m8fgCIFAAFUAAoAESBGEQoG0AE9QAAJe1qJoYFBwEikioYeoxNQGyDhagm0AAMlA5stRArCCrcAwoFhMXSoB6dGgWmFnXDZIpylAvxiGFG3FAOgAVqFVChjmPcDF4olVI90rgMJZVAAvKWEwdgb0ahXdneWDTIO0QByJNDgVM5oE5DXkCBoJ_Jo0hcDxDOKArgqMSPs-ph4ieECgNAkSDKoXrqJglgwEBSaJKYr7jt24C5BCxieEyUTIHCu43ng4DFjBdA5HaaBAdBjQaPKpgIAAjpYehjm2OF0G2r71tatr2ik0EACqrm-ApSuhHyXuRt4xBxXEaDxIHSfR6FwU0QymF6Gh6uenz0AGQYXNwwR0DGJS6cksRngaCp-qZvzGgEQI2ZELIeLEQlEDadoOi53y_G0oDhsujmGgA2osAC6IUBk6ETdsZhgCkKSCxDF8XuQEzGsYqxyBaJOV5eCWB4kQQpqOJdJsC6uX5XgTCQNQdD6CUCBqMchrlUy4Z1IgvVOaYvwlJR1H8bBtngi87X0F5dkutFzkoBoJQALKwI4mS2QhTJCpW3hmAAfOCAQ6QhDAoK8iBoHt9SnWdoDPUlvzmGYFjLAA_KAx3NqA-a5eCqIRWA116Suk0JNNbb8bwh6YLNkRfjERRYEW2XoNgb14qpO0wPInTlKoVY_QwACsLXZN-eSlRososTEP20xSRRVPV5BsMz8qxIy4KtpEGgyJhAskkuDGOGTqPgD5LiQBToD3HLCtKwCnm2T5RDhTp6smgA1IbIbgrLwKssVaBdSNxypj9JIBGtKRSxIAHwtyNi7A4jiDGNy1MqWu4wIrJqmx5HmzG93EWH7hrLTF-vuKH8WOx5TDAY4zHhxHHlxwqGWCsKkDQrC8I-NHLP5sxTImoHKEwPmQeoaHoBTGnEdG4bHceRbHhWzbPV28bPcBMLehiyYI-XW34Lt-CdOc3AjN8zEhsWH3SrHIPo2pmAABMaeFQqVuMykMJwo4i8MyJTNygg4MXBzN9BavoDr8yIID91u8RaAh8L0sqoOgW1qq1W5o1WIm9v62zQKmHgoAACMacqpEBqt8CB58y7alzqAREDAzTfmfLdFUODcG-FAP6X4-YQFgIwQ1UwEwWoR0cAAfSZGwF6gRn5cwam_Q2oA2DvyQTPcyHlH7cPprwnm_CN46xgUPOBacM5OGgdvH-dsvo_RzhHBaHUd59WchfeEScKihwkeiNEJMAjDkpGCCOUM8ygBihXIgu40B9HzPnIghcsrIAmBVCO9QCZ6CJiDGeoZyFwGTLQfM1QYCaj6FuQY1RmGRw0WNfMhCfwkOwOMShrlcA0OWghRhTI2FHRejPXRbUOolL0qkcgLFqBEEcEwbw_1aKGWBgDapoADh3Q0A9PaYdzCvSrAAQm-m-QyRE-lCgAEpRC2PmSJ5CCLHHzNSQZwyKkAy4RMvRS0DoNKFE0ywLS2mtD6UwvprZG6gGqFTKmABSVJfSDRqHwPmRBiwZ6WI8oEjy_lwm4LWbncMd0TCqHAA2VAy5NpBT_DNOwPNQBYESI1PppY2pNhND8tJY8YkIDicfd56yMX4rrKABBixqaEoBlUKUzF8x0ppn02FeIIGrL6QEKhRSVY3IZfiWky8so8vWQEMijx8woD0IMIVHKGyMwlZKqWGKCBSizvfHRkqo5tWVsfLeaAz6pErMIFA2qWYSPWSotpGszo_RrLWI5nUMm-kBiaC19rRmAhRPYyVEdbEOH8mfGKBrU68o8gCwNwbHnVFHtGhlAQlxVAAOoICYF8px1RtBGEgNUG5_y0ngojuGcAaUlDQDgRAOFUsxwMJnHQDQyZsVljxQSvpOkslEOTI4ceotMIDNeBoRw1QWgMuibEx5w1FHJnJeQgkNVvZxLzQQbAC7cGcqINygNtqmVoGYm03szZdW2szqg9BdUGFmubN6z13hHUqzPZKuNcqHQIETRHGNr6hgjjHGgeUX627JoKaFAVAAOJktJhSqmieUVZoAtyQGoaAAAzLPdZP6rERyBQEZMFo8Qg1LchXFJ6qWIKZHQPCJLHnI0JCEE05zqAFrnnhtKmTnERLucS1diRN253oJQagqr1lUuqCaATuDkykvvoWrDDKQD-Q7ZR0ABGGwqb6cp8jJBGRqcI42HTfzcE_vYziyAoLc4V3KLmfMaG9OfO-aAKmemlCRCFCquAgGEC3LBQU2z6GHNZqcy5pkbnwAedviQLz_NTOdA5PIdEUdZ2jX6hYGK1QzSpMeTIbL1R9B5ZjNUSN3jlo5Wcb8pklWVZMgSkyGKNXQAAHYmRQZVnlZxAA2JkABOJkLXQCdfiqASN8hJze1iJQTKwoxR0ElDKe-SoVQ-i1KV2yYX3UKnaEAA)

Hi @helgasoft , really appreciate your help! I am sorry because I have another question regarding this solution. Is it possible to apply this solution to bar chart with multiple series of data? The bar chart is something like this - [https://codesandbox.io/p/sandbox/9t5jj2](url) Thank you!

**Comment by ishaC02** [comment] 2025-01-23 07:11
@shiraineko, is the above demo code compatible with multiple series of data?

**Comment by shiraineko** [comment] 2025-01-23 13:22
> [@shiraineko](https://github.com/shiraineko), is the above demo code compatible with multiple series of data?

Based on my understanding, the demo code is for single series of data. Unfortunately, I am not capable of modifying it to work with multiple series of data.
