### ISSUE TITLE
[Bug] There is a conflict between the barMinHeight property and the stack property

### ISSUE THREAD

**Issue by TaurusWood** [apache/echarts#17733] opened 2022-10-08 03:33 UTC
### Version

5.4.0

### Link to Minimal Reproduction

https://codesandbox.io/s/stacked-column-chart-forked-27lr1z?file=/index.js

### Steps to Reproduce

1. Observe the first bar of the stacked column chart. When there is too little data, the labels overlap, although I set the barMinHeight property

### Current Behavior

1. barMinHeight is invalid in the stacked bar chart, which will cause the label values to overlap.

### Expected Behavior

The `barMinHeight ` property should have a higher priority in the stacked bar chart, otherwise it will display an error.

### Environment

```markdown
- OS: win11
- Browser: Chrome 106.0.5249.103
- Framework: react18
```

**Comment by Ovilia** [comment] 2023-01-10 07:14
Duplicate of #17005

**Closed by Ovilia** 2023-01-10 07:14 UTC
Labels: bug, pending, duplicate, en
