### ISSUE TITLE
[Bug] setOption替换合并series，labelLayout无法删除

### ISSUE THREAD

**Issue by WangYIlo** [apache/echarts#20416] opened 2024-10-14 06:04 UTC
### Version

5.5.1

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/basic-bar-forked-q3k6mw?file=%2Findex.js%3A24%2C20

### Steps to Reproduce

老的option中存在labelLayout，采用setOption替换合并新的series不存在labelLayout，合并后labelLayout仍然存在

### Current Behavior

替换合并后labelLayout仍然存在

### Expected Behavior

labelLayout应该被删除

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment] 2024-10-14 08:52
This is not a bug.

Please read the [doc](https://echarts.apache.org/zh/api.html#echartsInstance.setOption) carefully.

When using replace merge, series is merged based on id. So when you calling `setOption` for the second time, labelLayout is not provided and thus the old labelLayout is used (merged).

To fully reset the series, you need to set a different `series.id` the second time you calling `setOption`, or you can set `notMerge` to be `true` to force not using merging.

**Closed** 2024-10-14 08:53 UTC
Labels: en, not-a-bug
