### ISSUE TITLE
[Feature] can you upgrade tsconfig target >= "ES6"

### ISSUE THREAD

**Issue by triajidhan** [apache/echarts#19304] opened 2023-11-16 02:46 UTC
### What problem does this feature solve?

Option 'target=ES3' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error

### What does the proposed API look like?

-

**Comment by sparr** [comment] 2023-11-28 14:53
Per https://github.com/microsoft/TypeScript/issues/51909:

> ### What should I use instead?
> #### `target: ES3`
> ES3 runtimes are nearly 100% extinct, so we're removing support for this as an emit target.
> 
> Fix: Use `target: ES5` as the next-closest thing along with a linter to detect any potentially-problematic ES3 constructs, or use `target: ESNext` and use a different downleveling emitter.

**Comment by septatrix** [comment] 2024-01-24 10:01
We are currently already at TS 5.3...

**Comment by dohuuhuy** [comment] 2024-02-02 05:02
how to fix : 
Option 'target=ES3' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error. 
 
 tôi đang cần gấp

**Comment by plainheart** [comment] 2024-02-02 15:36
duplicate of #19560. Please follow #19560.

**Closed by plainheart** 2024-02-02 15:36 UTC
Labels: new-feature, pending, duplicate, en
