### ISSUE TITLE
[Bug] The algorithm problem of the proportion of bar stack when the y-axis type is log

### ISSUE THREAD

**Issue by leleccccc** [apache/echarts#19234] opened 2023-10-23 03:35 UTC
### Version

5.4.3

### Link to Minimal Reproduction

Official Editor

### Steps to Reproduce

`option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  tooltip: {
    trigger: 'axis'
  },
  yAxis: {
    type: 'log'
  },
  series: [
    {
      data: [150, 230, 224, 218, 136, 148, 260],
      type: 'line',
      stack: 'lineData'
    },
    {
      data: [75, 115, 112, 109, 68, 74, 130],
      type: 'bar',
      stack: 'barData'
    },
    {
      data: [75, 115, 112, 109, 68, 74, 130],
      type: 'bar',
      stack: 'barData'
    }
  ]
};`

### Current Behavior

![20231023-112809](https://github.com/apache/echarts/assets/39856276/ff2da89d-352a-45fd-bc7b-2f3c74a0129d)

### Expected Behavior

In this case, I hope that the stacking ratio of their bars is evenly divided because my data is set to half

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment] 2023-10-23 14:41
duplicate of #18330, #17960

**Comment by Ovilia** [comment] 2023-10-24 03:59
It seems many developers have related requirement. @helgasoft What do you think, should we support this?

**Comment by helgasoft** [comment] 2023-10-24 05:13
Well, it is already supported - bars are stacked. 
But the axis is nonlinear, so the **proportions** of stacked bars will always be incorrect.
Therefore the concept of using stacked bars in a log chart does not make sense as I explained in #18330.

[This demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=EYQwTmAEC8kN6QC4E8AOBTAXJARKMOANJAM6IgDGA1tjogPbkA2RkA-gJaLoC2AyiiZY49VJS7JMABgB0AVkgBfRYQCwAKFGIO9AHYx4GyJCEBzdLoAm2OCqNJ69JttQ27645ZDkS6RDftjEnoAVzAKLEgAbUDjaJxUMHpLEIpEVhwAJikARjkM7JyANgLcgHYcAF01DzjjKJwAYUcqDnRWbKkpYk7iHK6u6shY-pwAISSAd102jq6-ge7ITqXIatjK-3djBidgegAPTDgAM3RvMOEeEFMOCgAVNGEUDEwogHIySip3yuVtyAHACCBw4JBsSCetAo3nQpnoYGQOCUNWMyBBYIhL0iOCY9FMrGuRxWSx4HF0mByKPsvjAbXB0Vi-DAxGZrPAYHsm3UigA3EA) shows it again - **first** entry in each group has correct (measurable) size, The **total** height for each group is correct also, But everything in-between is "fake size".
The solution would be to use regular non-stacked bars, click on the stack icon to see the difference.

**Comment by leleccccc** [comment] 2023-10-24 08:07
@helgasoft From the perspective of y-axis values, the height of the column is correct, but from the comparison between the incoming data, the height of the column is incorrect. Can parameters be passed in to control the reference for column height when stacking with y-axis as a logarithm? For most users, they may feel that the second option is easier to understand, and they do not pay attention to the corresponding relationship between column height and y-axis values at this time

**Comment by Ovilia** [comment] 2023-10-24 08:53
@leleccccc As you stated, it's conflicting with the height and the stacked value. Even if there is an option for the developer, it may be misleading to users. So I would suggest not using stacked bars with log axis anyway.

**Closed** 2024-01-17 07:54 UTC
Labels: bug, en, wontfix, topic: stack
